
#pragma once

enum {
	CEPluginName=0,
	CEPluginMsgTitle,
	CELngEdit,
	CELngView,
	CELngTemp,
	CEConsoleOutput,
	CEStopSynchroWaiting,
	CEMenuEditOutput,
	CEMenuViewOutput,
	CEMenuShowHideTabs,
	CEMenuNextTab,
	CEMenuPrevTab,
	CEMenuCommitTab,
	CEMenuShowTabsList,
	CEMenuGuiMacro,
	CEMenuAttach,
	CEMenuDebug,
	CEGuiMacroTitle,
	CEGuiMacroCommand,
	CEGuiMacroResult,
	CEGuiMacroExecute,
	CEGuiMacroCancel,
	CEUnavailableInTerminal,
	CEAlreadyDebuggerPresent,
	CECantDebugInTerminal,
	CECantDebugNotEnvVar,
	CECantStartDebugger,
	CECantStartServer,
	CECantStartServer2,
	CECantStartServer3,
	CEInvalidConHwnd,
	CEShellExecuteException,
	CEColorMappingCreateError,
	CEGetAllTabsFailed,
	CEBkError_ExecFailed,
	CEBkError_InvalidArg,
	CEBkError_PluginForbidden,
	CEBkError_ConEmuInShutdown,
	CEBkError_Unexpected,
	CEBkError_InvalidArgSize,
	CEBkError_InvalidArgProc,
	};
