
#pragma once

#define CERR_FIRSTEXITCODE 100

typedef int CERR_EXIT_CODES;
const CERR_EXIT_CODES
	CERR_GETCOMMANDLINE = CERR_FIRSTEXITCODE+0,
	CERR_CARGUMENT = CERR_FIRSTEXITCODE+1,
	CERR_CMDEXENOTFOUND = CERR_FIRSTEXITCODE+2,
	CERR_NOTENOUGHMEM1 = CERR_FIRSTEXITCODE+3,
	CERR_CREATESERVERTHREAD = CERR_FIRSTEXITCODE+4, //-V112
	CERR_CREATEPROCESS = CERR_FIRSTEXITCODE+5,
	CERR_WINEVENTTHREAD = CERR_FIRSTEXITCODE+6,
	CERR_CONINFAILED = CERR_FIRSTEXITCODE+7,
	CERR_GETCONSOLEWINDOW = CERR_FIRSTEXITCODE+8,
	CERR_EXITEVENT = CERR_FIRSTEXITCODE+9,
	CERR_GLOBALUPDATE = CERR_FIRSTEXITCODE+10,
	CERR_WINHOOKNOTCREATED = CERR_FIRSTEXITCODE+11,
	CERR_CREATEINPUTTHREAD = CERR_FIRSTEXITCODE+12,
	CERR_CONOUTFAILED = CERR_FIRSTEXITCODE+13,
	CERR_PROCESSTIMEOUT = CERR_FIRSTEXITCODE+14,
	CERR_REFRESHEVENT = CERR_FIRSTEXITCODE+15,
	CERR_CREATEREFRESHTHREAD = CERR_FIRSTEXITCODE+16,
	CERR_HELPREQUESTED = CERR_FIRSTEXITCODE+18,
	CERR_ATTACHFAILED = CERR_FIRSTEXITCODE+19,
	CERR_RUNNEWCONSOLE = CERR_FIRSTEXITCODE+21,
	CERR_CANTSTARTDEBUGGER = CERR_FIRSTEXITCODE+22,
	CERR_CREATEMAPPINGERR = CERR_FIRSTEXITCODE+23,
	CERR_MAPVIEWFILEERR = CERR_FIRSTEXITCODE+24,
	CERR_COLORERMAPPINGERR = CERR_FIRSTEXITCODE+25,
	CERR_EMPTY_COMSPEC_CMDLINE = CERR_FIRSTEXITCODE+26,
	CERR_CONEMUHK_NOTFOUND = CERR_FIRSTEXITCODE+27,
	CERR_CONSOLEMAIN_NOTFOUND = CERR_FIRSTEXITCODE+28,
	CERR_HOOKS_WAS_SET = CERR_FIRSTEXITCODE+29,
	CERR_HOOKS_FAILED = CERR_FIRSTEXITCODE+30,
	CERR_DLLMAIN_SKIPPED = CERR_FIRSTEXITCODE+31,
	CERR_ATTACH_NO_CONWND = CERR_FIRSTEXITCODE+32, //-V112
	CERR_GUIMACRO_SUCCEEDED = CERR_FIRSTEXITCODE+33,
	CERR_GUIMACRO_FAILED = CERR_FIRSTEXITCODE+34,
	CERR_SERVER_ALREADY_EXISTS = CERR_FIRSTEXITCODE+35,
	CERR_RUNNEWCONSOLEFAILED = CERR_FIRSTEXITCODE+36
	;

#define CERR_LASTEXITCODE (CERR_FIRSTEXITCODE+100)
