
/*
Copyright (c) 2016-present Maximus5
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the authors may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#pragma once

#include "LngDataEnum.h"

static LngPredefined gsDataRsrcs[] = {
	{ lng_AboutAppName,             L"Console Emulation program (local terminal)" },
	{ lng_AltNumberACP,             L"Type ANSI code point using decimal numbers" },
	{ lng_AltNumberExt,             L" - <Enter> to paste, <Esc> to cancel" },
	{ lng_AltNumberHex,             L"Type UNICODE code point using hexadecimal numbers" },
	{ lng_AltNumberStdACP,          L" - release <Alt> to paste ANSI code point" },
	{ lng_AltNumberStdOEM,          L" - release <Alt> to paste OEM code point" },
	{ lng_AltNumberStdUCS,          L" - release <Alt> to paste UNICODE code point" },
	{ lng_AlternativeIsOffHint,     L"Alternative mode is off" },
	{ lng_AlternativeIsOnHint,      L"Alternative mode is ON (console frozen)" },
	{ lng_AssertAbortDescr,         L"Press <Abort> to throw exception, ConEmu will be terminated!" },
	{ lng_AssertIgnoreDescr,        L"Press <Ignore> to continue your work." },
	{ lng_AssertRetryDescr,         L"Press <Retry> to copy text information to clipboard\r\nand report a bug (open project web page)." },
	{ lng_BasicSettings,            L"Basic settings" },
	{ lng_BufferHeightOffHint,      L"BufferHeight mode is off" },
	{ lng_BufferHeightOnHint,       L"BufferHeight mode is ON (scrolling enabled)" },
	{ lng_CloseAllConsolesHint,     L"Close ALL consoles" },
	{ lng_ConfirmCloseActiveOnly,   L"Close active console only" },
	{ lng_ConfirmCloseBtn,          L"Close" },
	{ lng_ConfirmCloseBtnAll,       L"Close all" },
	{ lng_ConfirmCloseBtnConsole,   L"Close 1 console" },
	{ lng_ConfirmCloseBtnConsoles,  L"consoles" },
	{ lng_ConfirmCloseBtnGroup,     L"Close group of" },
	{ lng_ConfirmCloseChildGuiQ,    L"Confirm closing active child window?" },
	{ lng_ConfirmCloseConsoleQ,     L"Confirm closing console?" },
	{ lng_ConfirmCloseEditorQ,      L"Confirm closing Far editor?" },
	{ lng_ConfirmCloseGroupQ,       L"Confirm closing group?" },
	{ lng_ConfirmCloseViewerQ,      L"Confirm closing Far viewer?" },
	{ lng_ConfirmClosingQ,          L"Confirm closing?" },
	{ lng_ConfirmDontCloseAnything, L"Don't close anything" },
	{ lng_ConfirmIncompleteOperations,L"Incomplete operations" },
	{ lng_ConfirmKillButShellQ,     L"Terminate all but shell processes?" },
	{ lng_ConfirmKillingQ,          L"Confirm killing?" },
	{ lng_ConfirmUnsavedEditors,    L"Unsaved editor windows" },
	{ lng_CreateNewConsoleHint,     L"Create new console" },
	{ lng_CurClrScheme,             L"<Current color scheme>" },
	{ lng_DetachConConfirm,         L"Detach console from ConEmu?" },
	{ lng_DetachGuiConfirm,         L"Detach GUI application from ConEmu?" },
	{ lng_DlgAbout,                 L"About" },
	{ lng_DlgAffinity,              L"Set active console processes affinity and priority" },
	{ lng_DlgAttach,                L"Attach: Choose window or console application" },
	{ lng_DlgCreateNewConsole,      L"Create new console" },
	{ lng_DlgFastCfg,               L"fast configuration" },
	{ lng_DlgHotkey,                L"Choose hotkey" },
	{ lng_DlgRenameTab,             L"Rename tab" },
	{ lng_DlgRestartConsole,        L"Restart console" },
	{ lng_DlgSettings,              L"Settings" },
	{ lng_ExitCode,                 L"exit code" },
	{ lng_HkGlblGnrlMsg,            L"You can't choose distinctive (R/L) modifier for Global hotkeys due to WinAPI limitation" },
	{ lng_HotkeyDuplicated,         L"Hotkey <%s> is not unique" },
	{ lng_HotkeysAll,               L"All hotkeys" },
	{ lng_HotkeysFilter,            L"Filter hotkeys (Alt+F)" },
	{ lng_HotkeysMacro,             L"Macros" },
	{ lng_HotkeysSystem,            L"System" },
	{ lng_HotkeysUser,              L"User defined" },
	{ lng_JumpListUpdated,          L"Taskbar jump list was updated successfully" },
	{ lng_KeyNoMod,                 L"<No-Mod>" },
	{ lng_KeyNone,                  L"<None>" },
	{ lng_MaximizeWindowHint,       L"Maximize window" },
	{ lng_MenuAbout,                L"&About / Help" },
	{ lng_MenuAllTaskTabs,          L"All task tabs" },
	{ lng_MenuAlwaysOnTop,          L"Al&ways on top" },
	{ lng_MenuAttachTo,             L"Attach to..." },
	{ lng_MenuAutoScroll,           L"Auto scro&ll" },
	{ lng_MenuBringHere,            L"Bring &here" },
	{ lng_MenuChangeAffinity,       L"A&ffinity/priority..." },
	{ lng_MenuCheckUpdate,          L"&Check for updates" },
	{ lng_MenuChildSysMenu,         L"Child system menu..." },
	{ lng_MenuClearHistory,         L"Clear history..." },
	{ lng_MenuCloseConsole,         L"&Close console" },
	{ lng_MenuCloseGroup,           L"&Close tab group" },
	{ lng_MenuCloseTab,             L"&Close tab" },
	{ lng_MenuConCopy,              L"Cop&y" },
	{ lng_MenuConCopyAll,           L"Copy &all" },
	{ lng_MenuConCopyFmt0,          L"Plain &text only" },
	{ lng_MenuConCopyFmt1,          L"Copy &HTML format" },
	{ lng_MenuConCopyFmt2,          L"Copy a&s HTML" },
	{ lng_MenuConCopyFmt3,          L"A&NSI sequences" },
	{ lng_MenuConFind,              L"&Find text..." },
	{ lng_MenuConMarkBlock,         L"Mark &block" },
	{ lng_MenuConMarkText,          L"Mar&k text" },
	{ lng_MenuConPaste,             L"&Paste" },
	{ lng_MenuConProperties,        L"&Properties..." },
	{ lng_MenuConToggleVisible,     L"&Real console" },
	{ lng_MenuDebugActive,          L"Debug &active process..." },
	{ lng_MenuDebugAssert,          L"Show assertion" },
	{ lng_MenuDebugGui,             L"Debug &log (GUI)" },
	{ lng_MenuDebugShowRects,       L"Show debug rec&ts" },
	{ lng_MenuDebugTrap,            L"Raise exception (Main thread)" },
	{ lng_MenuDebugTrap2,           L"Raise exception (Monitor thread)" },
	{ lng_MenuDetach,               L"Detach" },
	{ lng_MenuDonateLink,           L"&Donate ConEmu" },
	{ lng_MenuDumpConsole,          L"&Dump screen..." },
	{ lng_MenuDumpMemBlk,           L"Dump used memory blocks" },
	{ lng_MenuDuplicate,            L"Duplica&te root..." },
	{ lng_MenuHelp,                 L"&Help" },
	{ lng_MenuHideToTray,           L"Hide to &TSA" },
	{ lng_MenuHomePage,             L"&Visit home page" },
	{ lng_MenuHotkeys,              L"Hot&keys" },
	{ lng_MenuLoadDumpConsole,      L"&Load screen dump..." },
	{ lng_MenuMiniDump,             L"Active process &memory dump..." },
	{ lng_MenuMiniDumpTree,         L"Active &tree memory dump..." },
	{ lng_MenuMoreTasks,            L"&More tasks" },
	{ lng_MenuNewConsole,           L"New console dialog..." },
	{ lng_MenuOnlineHelp,           L"Online &Help" },
	{ lng_MenuPopupActiveCon,       L"Acti&ve console" },
	{ lng_MenuPopupConList,         L"Console &list" },
	{ lng_MenuPopupDebug,           L"&Debug" },
	{ lng_MenuPopupEdit,            L"Ed&it" },
	{ lng_MenuPopupHelp,            L"Hel&p" },
	{ lng_MenuPopupPalettes,        L"&View (palettes)" },
	{ lng_MenuPopupRestart,         L"&Restart or duplicate" },
	{ lng_MenuPopupSysDebug,        L"&Debug" },
	{ lng_MenuPopupSysEdit,         L"&Edit" },
	{ lng_MenuPopupTerminate,       L"Close or &kill" },
	{ lng_MenuRenameTab,            L"Rena&me tab..." },
	{ lng_MenuReportBug,            L"&Report a bug..." },
	{ lng_MenuResetTerminal,        L"&Reset terminal" },
	{ lng_MenuRestart,              L"&Restart" },
	{ lng_MenuRestartAs,            L"Restart as Admin" },
	{ lng_MenuRestartDlg,           L"&Restart..." },
	{ lng_MenuRestoreFromTray,      L"Restore from &TSA" },
	{ lng_MenuScreenshot,           L"Make &screenshot..." },
	{ lng_MenuSettings,             L"Sett&ings..." },
	{ lng_MenuSetupTasks,           L"Setup tasks..." },
	{ lng_MenuSplit2Bottom,         L"Split to &bottom" },
	{ lng_MenuSplit2Right,          L"Split to ri&ght" },
	{ lng_MenuStopUpdate,           L"&Stop updates checking" },
	{ lng_MenuSysAttachTo,          L"Attach t&o..." },
	{ lng_MenuSysNewConsole,        L"New console dialog..." },
	{ lng_MenuTerminate2Right,      L"Close to the &right" },
	{ lng_MenuTerminateAllCon,      L"Close &all consoles" },
	{ lng_MenuTerminateButShell,    L"Kill all but &shell" },
	{ lng_MenuTerminateCon,         L"Close active &console" },
	{ lng_MenuTerminateConExpt,     L"Close e&xcept active" },
	{ lng_MenuTerminateGroup,       L"Close active &group" },
	{ lng_MenuTerminatePrc,         L"Kill &active process" },
	{ lng_MenuTerminatePrcGroup,    L"Kill active &processes" },
	{ lng_MenuTerminateZombies,     L"Close all &zombies" },
	{ lng_MenuUnfasten,             L"Unfasten" },
	{ lng_MenuWhatsNewFile,         L"Whats &new (local)" },
	{ lng_MenuWhatsNewWeb,          L"Whats new (&web)" },
	{ lng_MinimizeWindowHint,       L"Minimize window" },
	{ lng_NewConsoleSaveBtn,        L"&Save" },
	{ lng_NewConsoleStartBtn,       L"&Start" },
	{ lng_PasteEnterConfirm,        L"Warning!\n\nPasting multi-line text involves\nsending <Enter> keypresses to console!\n\nContinue?" },
	{ lng_PasteLongConfirm,         L"Warning!\n\nPasting long text (%u chars) may make the console\nnon-responsive until the paste finishes!\n\nContinue?" },
	{ lng_PleaseCheckManually,      L"Please check for updates manually" },
	{ lng_RasterAutoError,          L"Font auto size is not allowed for a fixed raster font size. Select ‘Terminal’ instead of ‘[Raster Fonts ...]’" },
	{ lng_ResetTerminalCancel,      L"Cancel operation" },
	{ lng_ResetTerminalConfirm,     L"Do you want to reset terminal contents?" },
	{ lng_ResetTerminalOk,          L"Reset terminal contents and properties" },
	{ lng_ResetTerminalTitle,       L"Reset terminal confirmation" },
	{ lng_ResetTerminalWarning,     L"Warning!\nThis operation could harm further output of applications.\nIt's better to execute a dedicated command as `clear` or `cls`." },
	{ lng_Search,                   L"Search" },
	{ lng_SearchCtrlF,              L"Search (Ctrl+F)" },
	{ lng_SelBlock,                 L" block selection" },
	{ lng_SelChars,                 L" chars " },
	{ lng_SelStream,                L" stream selection" },
	{ lng_SetPgInfoNone,            L"(None)" },
	{ lng_ShowSystemMenuHint,       L"Show system menu (RClick for Settings)" },
	{ lng_SizeRadioCentered,        L"Centered" },
	{ lng_SizeRadioFree,            L"Free" },
	{ lng_SpgANSI,                  L"ANSI execution" },
	{ lng_SpgAppDistinct,           L"App distinct" },
	{ lng_SpgAppear,                L"Appearance" },
	{ lng_SpgBackgr,                L"Background" },
	{ lng_SpgChildGui,              L"Children GUI" },
	{ lng_SpgColors,                L"Colors" },
	{ lng_SpgComSpec,               L"ComSpec" },
	{ lng_SpgConfirm,               L"Confirm" },
	{ lng_SpgCursor,                L"Text cursor" },
	{ lng_SpgDebug,                 L"Debug" },
	{ lng_SpgDefTerm,               L"Default term" },
	{ lng_SpgEnvironment,           L"Environment" },
	{ lng_SpgFarMacros,             L"Far macros" },
	{ lng_SpgFarManager,            L"Far Manager" },
	{ lng_SpgFarViews,              L"Panel Views" },
	{ lng_SpgFeatures,              L"Features" },
	{ lng_SpgFonts,                 L"Fonts" },
	{ lng_SpgGeneral,               L"General" },
	{ lng_SpgHighlight,             L"Highlight" },
	{ lng_SpgInfo,                  L"Info" },
	{ lng_SpgIntegration,           L"Integration" },
	{ lng_SpgKeyboard,              L"Keyboard" },
	{ lng_SpgKeys,                  L"Keys & Macro" },
	{ lng_SpgMarkCopy,              L"Mark/Copy" },
	{ lng_SpgMouse,                 L"Mouse" },
	{ lng_SpgPaste,                 L"Paste" },
	{ lng_SpgQuake,                 L"Quake style" },
	{ lng_SpgSizePos,               L"Size & Pos" },
	{ lng_SpgStartup,               L"Startup" },
	{ lng_SpgStatusBar,             L"Status bar" },
	{ lng_SpgTabBar,                L"Tab bar" },
	{ lng_SpgTaskBar,               L"Task bar" },
	{ lng_SpgTasks,                 L"Tasks" },
	{ lng_SpgTransparent,           L"Transparency" },
	{ lng_SpgUpdate,                L"Update" },
	{ lng_UnknownSwitch1,           L"Unknown switch specified:" },
	{ lng_UnknownSwitch2,           L"Visit website to get thorough switches description:" },
	{ lng_UnknownSwitch3,           L"Or run ‘ConEmu.exe -?’ to get the brief." },
	{ lng_UnknownSwitch4,           L"Switch ‘-new_console’ must be specified *after* ‘-cmd’ or ‘-cmdlist’!" },
	{ lng_UpdateCloseMsg1,          L"Please, close all ConEmu instances before continuing" },
	{ lng_UpdateCloseMsg2,          L"ConEmu still running:" },
	{ /* empty trailing item for patch convenience */ }
};
