
/*
Copyright (c) 2016 Maximus5
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the authors may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#pragma once

static LngPredefined gsDataHints[] = {
	{ ID_DONATE_LINK,          L"Visit https://conemu.github.io/donate.html" },
	{ ID_HOMEPAGE,             L"Visit https://conemu.github.io/" },
	{ ID_REPORTBUG,            L"Create bug report or request new feature\r\nhttps://conemu.github.io/en/Issues.html" },
	{ IDM_DETACH,              L"Show RealConsole and detach it from ConEmu" },
	{ IDM_RESTART,             L"Restart current console\r\nHold Shift to popup Restart dialog" },
	{ IDM_RESTARTAS,           L"Restart current console as Admin (Vista+) or user (WinXP)\r\nHold Shift to popup Restart dialog" },
	{ IDM_RESTARTDLG,          L"Show ‘Restart current console’ dialog" },
	{ IDM_TERMINATEALLCON,     L"Do normal close of all consoles (tabs and panes)" },
	{ IDM_TERMINATEBUTSHELL,   L"Active console/pane: Terminate all except root process" },
	{ IDM_TERMINATECON,        L"Active console/pane: Do normal close" },
	{ IDM_TERMINATECONEXPT,    L"Close all tabs and panes except active console/pane" },
	{ IDM_TERMINATEGROUP,      L"Active group: Do normal close of each pane" },
	{ IDM_TERMINATEPRC,        L"Active console/pane: Terminate active process" },
	{ IDM_TERMINATEPRCGROUP,   L"Active group: Terminate active process in each pane" },
	{ IDM_TERMINATEZOMBIES,    L"Close ‘zombies’ (where ‘Press Esc to close console’ is displayed)" },
	{ IDM_UNFASTEN,            L"Open active console/pane in the new ConEmu window" },
	{ bRealConsoleSettings,    L"You may change font face and size in the Real console. Console restart required." },
	{ bReloadSettings,         L"Reload all settings from registry/xml" },
	{ bResetSettings,          L"Reset all settings to defaults" },
	{ bSaveSettings,           L"Save settings to registry/xml\r\nDon't close dialog if Shift pressed" },
	{ cbActivateSplitMouseOver, L"When several panes (splits) are visible simultaneously activate (put focus in) console with mouse hover,\r\n3rd-state - match ‘Active window tracking’ system settings" },
	{ cbAdminShield,           L"When this is checked - ‘Shield’ icon will be shown in tabs, started ‘As administrator’" },
	{ cbAdminSuffix,           L"When this is checked - specified suffix will be appended in tabs titles, started ‘As administrator’.\r\nYou may choose insertion place with ‘%a’ var, otherwise suffix will be at the tab end." },
	{ cbAlwaysOnTop,           L"Places the ConEmu window above all non-topmost windows. The window maintains its topmost position even when it is deactivated" },
	{ cbAlwaysShowTrayIcon,    L"Always show ConEmu icon in the Taskbar Status Area (TSA)" },
	{ cbAnsiLog,               L"Log console output to text files\r\nConEmu-YYYY-MM-DD-pNNNN.log\r\n(affect new consoles only)" },
	{ cbAutoRegFonts,          L"Search, register for process, and use first *.ttf file in conemu folder" },
	{ cbBgAllowPlugin,         L"Enable background Far plugins (e.g. Panel Colorer),\r\n3rd-state - don't draw in viewer/editor" },
	{ cbBgImage,               L"Show background image instead standard\r\ncolors #0 and #1 (black and blue)\r\n3rd-state - don't draw in viewer/editor" },
	{ cbBold,                  L"Main font weight" },
	{ cbClinkWebPage,          L"Open clink's web page https://mridgers.github.io/clink/ in your browser" },
	{ cbCloseConsoleConfirm,   L"Show confirmation before closing tab or page (tab ‘Close’ menu item)" },
	{ cbCloseEditViewConfirm,  L"Show confirmation before closing Far Manager editor or viewer tab" },
	{ cbCloseWindowConfirm,    L"Show confirmation before closing ConEmu window (cross clicking)" },
	{ cbComspecTest,           L"Show ‘calculated’ ComSpec path" },
	{ cbComspecUpdateEnv,      L"ConEmu may update %ComSpec% variable to selected command processor" },
	{ cbConfirmCloseRunning,   L"If there are two or more user processes in the console" },
	{ cbConsoleExceptionHandler, L"By default ConEmu doesn't do SetUnhandledExceptionFilter in alternative servers (Far, Telnet, etc.)\r\nBut it may be enabled for debugging purposes" },
	{ cbCTSAutoCopy,           L"Copy immediately on left mouse button up (when selecting with mouse)" },
	{ cbCTSBashMargin,         L"Bash leave one space-character on the right edge of console when wrapping lines, skip these spaces when copying to clipboard" },
	{ cbCTSBlockSelection,     L"Enable rectangular selection (like standard Windows console)" },
	{ cbCTSClickPromptPosition, L"3rd-state means ‘try to detect if console is in ReadConsole’, if you want to use this with bash - turn checkbox to ‘On’ (don't use third state)" },
	{ cbCTSDeleteLeftWord,     L"Delete word leftward to the cursor (ignored in Far),\r\n3rd-state means ‘try to detect if console is in ReadConsole’, if you want to use this with bash - turn checkbox to ‘On’ (don't use third state)" },
	{ cbCTSDetectLineEnd,      L"Try to copy wrapped text as single line when possible (Text selection)" },
	{ cbCTSEndCopyBefore,      L"Copy selection to clipboard before selection region reset" },
	{ cbCTSEndOnKeyPress,      L"When ‘Off’ - only characters ends selection\r\nWhen ‘On’ - any key ends selection (Arrows, PgUp, End, etc.)" },
	{ cbCTSEndOnTyping,        L"Reset selection region on keypress" },
	{ cbCTSEraseBeforeReset,   L"Try to erase selected region if possible\r\nby posting sequence of Del/BS to console.\r\nImplement ‘usual’ hotkeys Ctrl+X, Shift+Del, BS and Del." },
	{ cbCTSFreezeBeforeSelect, L"Freeze console contents before selection (may cause small lag)" },
	{ cbCTSIBeam,              L"Show IBeam (text selection) cursor when available and allowed by settings and key modifiers" },
	{ cbCTSResetOnRelease,     L"Reset selection region on left mouse button up (when selecting with mouse)" },
	{ cbCTSShiftArrowStartSel, L"Start text selection with Shift+Left/Right/Home/End or block selection with Shift+Up/Down" },
	{ cbCTSTextSelection,      L"Enable streaming selection (like GUI text editors)" },
	{ cbCTSTrimTrailing,       L"3rd-state means ‘Only for Text selection’" },
	{ cbCursorBlink,           L"When \"Blinking\" is ON - cursor blinks\r\nwith standard cursor blink rate." },
	{ cbCursorColor,           L"ON - cursor emulates console behaviour (sort of colors inversion)\r\nOFF - cursor is white (color#15) on dark backgrounds,\r\nand black (color#0) on light backgrounds; also this checkbox affect appearance of ‘Block’ cursors" },
	{ cbCursorIgnoreSize,      L"Ignore cursor size in real console, always show cursor with specified size" },
	{ cbDebugSteps,            L"Show some debug information in ConEmu title\r\nE.g. plugin communication steps." },
	{ cbDefTermAgressive,      L"If enabled, running ConEmu instance will not be required for hooking new processes. One already hooked process, e.g. ‘Explorer.exe’, will be enough." },
	{ cbDisableAllFlashing,    L"Disable all flashing (from consoles) on Windows taskbar.\r\n3rd-state - allow short flashing." },
	{ cbDisableFarFlashing,    L"Disable flashing (from Far Manager) on Windows taskbar.\r\n3rd-state - allow short flashing." },
	{ cbDnDCopy,               L"Forced \"Copy\" action as default,\r\nYou can use Ctrl, Shift or Alt\r\nduring drag to change action" },
	{ cbDosBox,                L"Enables DosBox integration" },
	{ cbDragIcons,             L"Show icons of dragged items" },
	{ cbDragImage,             L"Create and display overlay transparent snapshot of files are dragged" },
	{ cbDragL,                 L"Allow drag with left mouse button" },
	{ cbDragPanel,             L"Enable sizing of left and right panel by dragging with mouse.\r\n3rd-state - resize on button release with macroses." },
	{ cbDragR,                 L"Allow drag with right mouse button" },
	{ cbDropEnabled,           L"Off - ConEmu will NOT receive external drops\r\nOn - Drops allowed (Far confirmation dialog)\r\n3rd-state - same as \"On\", but w/o confirmation" },
	{ cbDropUnlocked,          L"Unlock source and target window on Drop operation. This may cause unpredictable results, when DragSource creates temp dragged files ONLY for drag lifetime." },
	{ cbDropUseBCopy,          L"Use BCopy service for drop operations (‘Unlocked drop’ must be checked)" },
	{ cbEnableMouse,           L"Uncheck this to stop sending mouse events to console, mouse will be processed by ConEmu internally (text selection, for example)" },
	{ cbEnhanceGraphics,       L"Enhance appearance of progressbars and scrollbars" },
	{ cbExportConfig,          L"Export your current settings to xml file\r\n\r\nBeware overwriting your current ConEmu.xml if you are using ConEmu portable mode!" },
	{ cbExtendColors,          L"You can use up to 32 foreground colors\r\n(instead of console standard 16) at the\r\nexpense of one of background colors" },
	{ cbExtendFonts,           L"ConEmu is able to use normal, bold and italic fonts side by side.\r\nThis feature may be useful for prompt decoration or with Colorer plugin for Far Manager (1.7x, 2.x)." },
	{ cbExtendUCharMap,        L"Show glyphs from selected font in ‘Unicode CharMap’ plugin (FAR2 only)" },
	{ cbFadeInactive,          L"When ConEmu loses focus, its contents may be faded. You may specify most bright color." },
	{ cbFarHourglass,          L"Show AppStarting cursor (arrow with a small hourglass) when Far is not responding (during long operations)" },
	{ cbFARuseASCIIsort,       L"Hook Far string sort functions.\r\n!!!HIGHLY EXPERIMENTAL!!!" },
	{ cbFixAltOnAltTab,        L"When You set a macro on Alt (RAlt) it can unexpectedly activates on AltTab or AltF9. This issue can be fixed by sending to console Control depress before Alt release." },
	{ cbFixFarBorders,         L"You can specify additional font for drawing pseudographics or specified range of symbols.\r\nE.g. main - \"Fixedsys\", additional - \"Lucida Console\".\r\nYou may force this font for specified range of symbols, search \"Settings-ConEmu.reg\" for \"FixFarBordersRanges\" option." },
	{ cbFocusInChildWindows,   L"Set focus in xshell/putty/notepad/etc. when ConEmu is activated or tab switched." },
	{ cbFontAuto,              L"Automatic font resize for the fixed real console width" },
	{ cbHandleFarDetach,       L"Automatic attach to ConEmu new Far manager console, created on detach (CtrlAltTab)" },
	{ cbHereName,              L"What you will see in the Explorer popup menu\r\nYou can use `&` sign to set hotkey for the menu item" },
	{ cbHideCaption,           L"Hide main window caption, when maximized (Alt-F9)" },
	{ cbHideCaptionAlways,     L"Remove window border and caption. Only console, tabs and status bar will be shown." },
	{ cbHideDisabledTabs,      L"Hide tabs, which can't be activated.\r\nE.g. hide Far Manager editors while executing cmd.exe" },
	{ cbHideInactiveConTabs,   L"Show tabs from active console only" },
	{ cbInjectConEmuHkFast,    L"Required for many features (ANSI X3.64, -new_console argument, GUI apps in ConEmu tabs, ...) and elimination of several problems (crash in Windows 8, telnet in Windows 7, dialogs and menus behind of ConEmu window, chcp hungs, and so on...)" },
	{ cbInsideName,            L"What you will see in the Explorer popup menu\r\nYou can use `&` sign to set hotkey for the menu item" },
	{ cbInsideSyncDir,         L"Sync current directory (Explorer -> ConEmu)" },
	{ cbInstallKeybHooks,      L"Allows interception of Win+Number, Win+Arrows, Alt+Esc, Alt+Tab, etc." },
	{ cbItalic,                L"Main font italic" },
	{ cbLongOutput,            L"Autoexpand bufferheight to specified\r\nnumber of lines, while Far executes\r\nconsole commands. Full console output\r\n(up to specified count of lines) will be\r\navailable via Far macro (CtrlO.reg)" },
	{ cbMinToTray,             L"Auto minimize to Taskbar Status Area (TSA)\r\nRight click on ‘Close window button’\r\nin ConEmu title for minimize to TSA,\r\nwhen this checkbox is OFF" },
	{ cbMonitorConsoleLang,    L"Monitor input language change in real\r\nconsole (e.g. Far Manager XLat switching support)" },
	{ cbMonospace,             L"Check it for non proportional (monospaced) fonts" },
	{ cbMultiCon,              L"Turn on MultiConsole\r\n(several consoles in one ConEmu)\r\nConEmu restart required" },
	{ cbMultiIterate,          L"Iterate opened Far windows with ‘Host-key’+Number" },
	{ cbNewConfirm,            L"Confirm new console creation.\r\nYou may change cmd line for it, or turn on \"Run as...\" feature.\r\nEven if unchecked, You may hold \"Shift\" to display dialog." },
	{ cbNumberInCaption,       L"Show [ActiveCon/TotalCon] in window caption" },
	{ cbOneTabPerGroup,        L"Show only one tab for all splits in the group" },
	{ cbProcessAnsi,           L"Enable processing of ANSI escape sequences, ‘Inject ConEmuHk’ must be checked if you want to work with second level processes (e.g. cmd.exe -> app.exe)" },
	{ cbProcessCmdStart,       L"Hook 'start' command in your cmd's prompt and batches started in ConEmu tabs to run console applications in new ConEmu tabs" },
	{ cbProcessCtrlZ,          L"Treat Ctrl-Z as ‘EndOfStream’. On new line press Ctrl-Z and Enter.\r\nRefer to the gh#465 for details (Go input streams)." },
	{ cbProcessNewConArg,      L"Enable processing of '-new_console' and '-cur_console' switches in your shell prompt, scripts etc. started in ConEmu tabs" },
	{ cbQuakeStyle,            L"Slide console window from the top of the screen like gaming consoles\r\nChoose desired hotkey for ‘Minimize/Restore’ action on ‘Keys & Macro’ page" },
	{ cbRClick,                L"Off - all RClicks passed to console\r\nOn - EMenu called instead of RClick\r\n3rd-state - Short RClick passed, Long RClick -> EMenu\r\nWarning! This may conflict with RDrag" },
	{ cbRestore2ActiveMonitor, L"When restoring or sliding-down move window to the active monitor, where mouse cursor is located" },
	{ cbRetardInactivePanes,   L"Retard inactive but visible split-panes in the active ConEmu window" },
	{ cbRSelectionFix,         L"Fix dashed selection with fast right mouse drag\r\nFar 3: restore files selection instead of EMenu" },
	{ cbSafeFarClose,          L"Try to close Far Manager softly, instead of closing console window, when you close ConEmu window" },
	{ cbSendAltEsc,            L"When checked, You can use \"Alt+Esc\" in Far internally" },
	{ cbSendAltPrintScrn,      L"When checked, You can use \"Alt+PrintScrn\" in Far internally" },
	{ cbSendAltTab,            L"When checked, You can use \"Alt+Tab\" in Far internally.\r\nWarning! This blocks ability of switching to another window" },
	{ cbSendCtrlEsc,           L"When checked, You can use \"Ctrl+Esc\" in Far internally" },
	{ cbSendPrintScrn,         L"When checked, You can use \"PrintScrn\" in Far internally" },
	{ cbShellNoZoneCheck,      L"SEE_MASK_NOZONECHECKS. Same as appeared in Far 2 build 771 and disappeared after 1464." },
	{ cbShowFarWindows,        L"Show all Far Manager windows (panels, editors, viewers) instead of one tab for one console" },
	{ cbShowHelpTooltips,      L"Don't like tooltips in settings dialog? Disable this feature." },
	{ cbShowWasHiddenMsg,      L"Show ‘ConEmu was hidden from some program’ message in TSA" },
	{ cbShowWasSetOnTopMsg,    L"Show ‘Some external program brought ConEmu OnTop. Revert?’ confirmation box" },
	{ cbSingleInstance,        L"Use one ConEmu window when starting new console from shortcut or somewhere\r\nMay be disabled by ‘/nosingle’ or forced by ‘/single’ switches" },
	{ cbSkipActivation,        L"Skip mouse button (left/right/middle)\r\nclick, while activating window" },
	{ cbSkipFocusEvents,       L"Don't send focus events to console to disable\r\nautoclosing of fast search dialog in panels" },
	{ cbSkipMove,              L"Skip mouse move events, while\r\nConEmu is not foreground window" },
	{ cbSleepInBackground,     L"Reduce FPS when ConEmu loses focus" },
	{ cbSnapToDesktopEdges,    L"Lock ConEmu window inside desktop work area" },
	{ cbStartFarRestoreEditors, L"When ‘Auto save/restore opened tabs’ save/restore Far Manager editors/viewers too" },
	{ cbStartFarRestoreFolders, L"When ‘Auto save/restore opened tabs’ save/restore Far Manager panels folders too" },
	{ cbSuppressBells,         L"Suppress annoying bells produced by echoing char(7), Beep and MessageBeep functions.\r\nInject ConEmuHk is required." },
	{ cbTabLazy,               L"When checked - real window switching\r\nwill be performed on Ctrl depress" },
	{ cbTabRecent,             L"Switch first between recent tabs.\r\nYou may still switch between tabs in\r\nstandard manner using Left/Right\r\n(after CtrlTab), while Ctrl is still presses." },
	{ cbTabs,                  L"Show tabs (all opened panels, editors and viewers)\r\non the top of ConEmu window" },
	{ cbTabSelf,               L"Handle CtrlTab and CtrlShiftTab internally\r\n(by ConEmu). These keystrokes will not be sent\r\nto console window, but You can easily\r\nswitch between consoles (panels)." },
	{ cbTabsOnTaskBar,         L"Represent each console on taskbar\r\n3rd-state - Windows 7 and higher" },
	{ cbThumbLoadFiles,        L"Generate previews for files" },
	{ cbThumbLoadFolders,      L"Generate previews for folders (by first 4 files)" },
	{ cbThumbRestoreOnStartup, L"Restore panel views on Far startup" },
	{ cbThumbUsePicView2,      L"Try to use PicView2 plugin to generate previews (FAR2 only)" },
	{ cbTrueColorer,           L"Colorer truemod support" },
	{ cbTryToCenter,           L"Draw console content in center of ConEmu window. Use together with ‘Pad size’" },
	{ cbUseClink,              L"Use clink to extend command prompt (cmd.exe)\r\nhttps://mridgers.github.io/clink/" },
	{ cbUseInjects,            L"Allow injecting ConEmuHk.dll in every process of ConEmu console window.\r\nRequired for many features (ANSI X3.64, -new_console argument, GUI apps in ConEmu tabs, ...) and elimination of several problems (telnet in Windows 7, dialogs and menus behind of ConEmu window, chcp hungs, and so on...)" },
	{ cbUseKeyboardHooksFast,  L"Required for some keyboard combinations. When checked, ConEmu will install keyboard hook when ConEmu is foreground window. So, You must allow that in antiviral software (AVP for example)" },
	{ cbUserScreenTransparent, L"Turn on ‘User screen’ transparency, when panel(s) is lifted up or hided. You may temporary reveal ‘User screen’ by depressing Ctrl-Alt-Shift." },
	{ cbUseWinArrows,          L"Resize ConEmu window with arrow keys" },
	{ cbUseWinNumber,          L"Enables switching of tabs (30 consoles) by their numbers (1,2,...,9,10,11,...). ‘Host-key’ is ‘Win’ key, by default." },
	{ cbUseWinTab,             L"Disable Windows 7 Aero switch (Win+Tab) when ConEmu in foreground" },
	{ cbVisible,               L"Show real console on startup" },
	{ lbCmdOutputCP,           L"Windows command processor (cmd.exe) may cause then output of internal commands to be OEM or Unicode.\r\nYou may force this selection, or use automatic selection (FAR2 -> Unicode)." },
	{ lbColorsOverride,        L"You may choose one of predefined color schemes.\r\nEach scheme customize 32 colors (16+16)\r\nand extend foreground options." },
	{ lbConClrBack,            L"Specify default background text color for new consoles" },
	{ lbConClrPopBack,         L"Specify default background popup color for new consoles" },
	{ lbConClrPopText,         L"Specify default foreground (font) popup color for new consoles" },
	{ lbConClrText,            L"Specify default foreground (font) text color for new consoles" },
	{ lbCTSBlockSelection,     L"Choose modifier to starting ‘Block selection’ with mouse LeftClick+Drag" },
	{ lbCTSEOL,                L"Choose preferred line separator (\\r\\n, \\n or \\r)" },
	{ lbCTSTextSelection,      L"Choose modifier to starting ‘Text selection’ with mouse LeftClick+Drag" },
	{ lbDefaultColors,         L"You may choose one of predefined color schemes.\r\nEach scheme customize 32 colors (16+16)\r\nand extend foreground options." },
	{ lbExtendFontBoldIdx,     L"Choose background color index for which ‘Bold’ font properties will be inverted (default is Red #12)" },
	{ lbExtendFontItalicIdx,   L"Choose background color index for which ‘Italic’ font properties will be inverted (default is Magenta #13)" },
	{ lbExtendFontNormalIdx,   L"When Bold or Italic font property was inverted, ConEmu may change background to default color (default is Blue #1)" },
	{ lbExtendIdx,             L"Choose background color index, used to increase foreground color index" },
	{ lbGotoEditorCmd,         L"Command line for starting editor with file positioned on line and column" },
	{ lbLDragKey,              L"Drag with left mouse button, only when pressed..." },
	{ lbNtvdmHeight,           L"Old DOS programs may be run under console sizes: 80x25, 80x28, 80x43 or 80x50. You may force window size selection, or left the automatic selection.\r\nThis feature is not available in x64 OS." },
	{ lbRDragKey,              L"Drag with right mouse button, only when pressed..." },
	{ rbActivityCmd,           L"Log internal ConEmu (GUI<-->Server) calls" },
	{ rbActivityDebug,         L"Automatically attach ConEmu debugger to all started processes" },
	{ rbActivityDisabled,      L"Disable debug logging. This implies on ‘Settings’ dialog close." },
	{ rbActivityInput,         L"Log keyboard and mouse activities" },
	{ rbActivityShell,         L"Log shell calls (progress creations, library loadings, etc.) ‘Inject ConEmuHk’ is required" },
	{ rbComspec_AppBit,        L"64bit OS only, (System32 or SysWOW64) - same bits as application (ConEmu, Far Manager, ...)" },
	{ rbComspec_OSbit,         L"64bit OS only, (System32 or SysWOW64) - use System32" },
	{ rbComspec_x32,           L"64bit OS only, (System32 or SysWOW64) - use SysWOW64" },
	{ rbComspecAuto,           L"Start tcc - if installed, %ComSpec% - otherwise (used for ‘Create new ‘cmd.exe’ console’)" },
	{ rbComspecCmd,            L"Use cmd.exe only (used for ‘Create new ‘cmd.exe’ console’)" },
	{ rbComspecEnvVar,         L"Use %ComSpec% environment variable (used for ‘Create new ‘cmd.exe’ console’)" },
	{ rbComspecExplicit,       L"Specified command processor (used for ‘Create new ‘cmd.exe’ console’)" },
	{ rbScrollbarAuto,         L"Show scrollbar on mousehover or scroll position change" },
	{ rbScrollbarHide,         L"Don't show scrollbar" },
	{ rbScrollbarShow,         L"Always show scrollbar on the right edge of window" },
	{ rbStartLastTabs,         L"Auto save/restore (reopen) ConEmu tabs" },
	{ rbStartNamedTask,        L"Starts ConEmu with several (one or more) tabs, commands located in ConEmu Settings, Tasks page" },
	{ rbStartSingleApp,        L"Starts ConEmu with single tab opened" },
	{ rbStartTasksFile,        L"Starts ConEmu with several (one or more) tabs, commands located in specified text file" },
	{ rCursorB,                L"Full cell (block) cursor, change ‘Color’ checkbox for changing cursor appearance" },
	{ rCursorH,                L"Horizontal text cursor, like native console" },
	{ rCursorV,                L"Vertical text cursor, like standard graphic text editors" },
	{ slTransparent,           L"Transparency of the main ConEmu window" },
	{ tAnsiLogPath,            L"You may choose folder for in-console log files\r\n(affect new consoles only)" },
	{ tBgImage,                L"Choose background image file (bmp, jpg, png, tif) or specify solid color in any form supported by ‘Colors’ page" },
	{ tBgImageColors,          L"Choose background color indexes,\r\nwhich will be replaced with background image,\r\ndefault is ‘#0 #1’ Black and Blue.\r\nUse \"*\" (asterisk) for Far Manager panels background color." },
	{ tCloseTabMacro,          L"Macro for close Editor/Viewer/Panels in Far Manager, when you choose ‘Close’ from tab context menu\r\nClear field to reset to defaults" },
	{ tCmdGroupCommands,       L"Commands (application, arguments, ‘-new_console’)\r\nDelimit commands with empty lines\r\nEach command creates tab or pane on group start\r\nMark active console tab with '>' sign\r\nStart console 'As Admin' with '*' sign" },
	{ tCmdGroupGuiArg,         L"Task parameters (‘/dir’, ‘/icon’)\r\nExample: /dir \"C:\\\" /icon \"cmd.exe\" /single" },
	{ tCmdGroupKey,            L"Choose hotkey for creating this task (not global, it works in ConEmu only)" },
	{ tCmdGroupName,           L"Task name (alias), surrounded by {...}, used in ‘[+] menu’, ‘Recreate dialog’ or ‘/cmd’ argument of ConEmu.exe" },
	{ tCursorFixedSize,        L"Specified size of cursor in percents. Use together with ‘Fixed cursor size’" },
	{ tCursorMinSize,          L"Specified minimal size of cursor in pixels (regardless of ‘Fixed cursor size’)" },
	{ tFadeHigh,               L"When ConEmu loses focus, its contents may be faded. You may specify here \"high shift\" (which makes light colors darker)." },
	{ tFadeLow,                L"When ConEmu loses focus, its contents may be faded. You may specify here \"low shift\" (which makes dark colors lighter)." },
	{ tFontCharset,            L"Main font charset" },
	{ tFontFace,               L"Face name for main font" },
	{ tFontFace2,              L"Font face used to draw pseudographics or specified range of symbols.\r\nE.g. main - \"Fixedsys\", additional - \"Lucida Console\".\r\nYou may force this font for specified range of symbols, search \"Settings-ConEmu.reg\" for \"FixFarBordersRanges\" option." },
	{ tFontSizeX,              L"Main font width\r\n0 - mean default width\r\nfor specified height" },
	{ tFontSizeX2,             L"WIDTH for pseudographics font.\r\nIt must be wider than main font,\r\notherwise, You may get \"dashed\" borders." },
	{ tFontSizeX3,             L"Cell width for \"Monospace\" mode" },
	{ tFontSizeY,              L"Main font height" },
	{ tHereConfig,             L"Allows to set different font, palette and other settings for your ConEmu instance" },
	{ tHereIcon,               L"‘C:\\Far\\far.exe,0’, ‘powershell.exe’, ‘C:\\Images\\Icon.ico’" },
	{ tHereShell,              L"Specify your shell here (cmd, far, etc.)\r\nUse ‘%1’ macro for ‘clicked’ item\r\nUse ‘!ConEmuWorkDir!’ for the directory,\r\nbut not a clicked file\r\nUse ‘/single /cmd shell’ to reuse existing ConEmu window instead of creating new one" },
	{ tHideCaptionAlwaysDelay, L"Delay in milliseconds, for a Frame appearance" },
	{ tHideCaptionAlwaysDissapear, L"Delay in milliseconds, for a Frame disappearance" },
	{ tHideCaptionAlwaysFrame, L"While caption and frame are hidden, ConEmu may keep small part of frame (in pixels) around console part. Default is 1 pixel." },
	{ tInsideConfig,           L"Allows to set different font, palette and other settings for your ConEmu instance" },
	{ tInsideIcon,             L"‘C:\\Far\\far.exe,0’, ‘powershell.exe’, ‘C:\\Images\\Icon.ico’" },
	{ tInsideShell,            L"Specify your shell here (cmd, far, etc.)\r\nUse ‘%1’ macro for ‘clicked’ item\r\nUse ‘!ConEmuWorkDir!’ for the directory,\r\nbut not a clicked file" },
	{ tInsideSyncDir,          L"Format of ‘cd’, default is ‘\\eCD /d \\1\\n’.\r\n\\e - ESC, \\b - BS, \\n - ENTER, \\1 - \"dir\", \\2 - \"bash dir\"." },
	{ tLongOutputHeight,       L"Length of backscroll buffer in lines.\r\nMaximum supported value is 32766." },
	{ tOptionSearch,           L"This allows to search all setup pages controls for specified text\r\nClick ‘zoom’ icon or press ‘Enter’ to continue search" },
	{ tPadSize,                L"Create pad between ConEmu frame and console field" },
	{ tPerfCounters,           L"FPS: Frames per second\r\nData: Average duration of transferring data from Real to Virtual console\r\nRender: Average duration of rendering text to memory DC\r\nBlt: Average duration of blit operation from memory DC to screen DC\r\nRPS: Average counts of reads real console data per second" },
	{ tQuakeAnimation,         L"Duration of window animation (0..2000ms): Quake slide down/up and restoring/hiding window to TSA.\r\nAnimation is working only when window caption is hidden." },
	{ tRClickMacro,            L"Far Manager macro for EMenu of file panel selected items\r\nClear field to reset to defaults" },
	{ tRealFontBorders,        L"Real sizes of \"Change pseudographics font\":\r\nHeight x Width" },
	{ tRealFontMain,           L"Real sizes of main font:\r\nHeight x Width x AveWidth" },
	{ tSafeFarCloseMacro,      L"Macro for close Far Manager softly, instead of closing console window, when you close ConEmu window\r\nClear field to reset to defaults" },
	{ tSaveAllMacro,           L"Macro for saving all opened Far Manager modified editors, when you choose ‘Save all’ from tab context menu\r\nClear field to reset to defaults" },
	{ tScrollAppearDelay,      L"Scrollbar appear delay when ‘Always show scrollbar’ is off or in 3rd-state" },
	{ tScrollDisappearDelay,   L"Scrollbar disappear delay when ‘Always show scrollbar’ is off or in 3rd-state" },
	{ tsTopPID,                L"Far PID and Far with plugin PID" },
	{ tStorage,                L"Current storage of ConEmu settings\r\nYou may change location by creating/deleting \"ConEmu.xml\" file\r\nAlso you may use /config \"Name\" command-line switch (ConEmu.exe) for multiple configurations" },
	{ tTabBarDblClickAction,   L"When you double click on the free space of tab bar...\r\n‘Auto’ means ‘Maximize/Restore’ when caption is hidden and ‘Open new shell’ when caption is visible" },
	{ tTabBtnDblClickAction,   L"When you double click on the tab..." },
	{ tTabConsole,             L"Common tab template (any console program except Far Manager)" },
	{ tTabEditor,              L"Tab template for Far Manager internal editors" },
	{ tTabEditorMod,           L"Tab template for Far Manager internal modified editors" },
	{ tTabFlashCounter,        L"When something was changed in the inactive console\r\nConEmu may flash tab icon in that case\r\nSet ‘-1’ to flash infinitely\r\nUse odd values to leave tab in highlighted state" },
	{ tTabModifiedSuffix,      L"When something was changed in the inactive console\r\nConEmu may show that in the tab label\r\nSet or clear this suffix appended to the tab template" },
	{ tTabPanels,              L"Tab template for Far Manager panels" },
	{ tTabViewer,              L"Tab template for Far Manager internal viewers" },
	{ tThumbLoadingTimeout,    L"Maximal duration of preview generation (per file)" },
	{ tThumbMaxZoom,           L"Maximal zoom for images smaller than preview" },
	{ tThumbsFontName,         L"Text labels font name in Thumbnails mode" },
	{ tThumbsFontSize,         L"Text labels font height in Thumbnails mode" },
	{ tThumbsImgSize,          L"Size in pixels of preview square in Thumbnails mode\r\nDefault is 96" },
	{ tThumbsPadding,          L"Horizontal spacing in pixels (left and right) of text label" },
	{ tThumbsSpacing,          L"Vertical spacing in pixels (top and bottom) of text label" },
	{ tThumbsX1,               L"Spacing in pixels from the left side of cell to the left side of preview" },
	{ tThumbsX2,               L"Spacing in pixels from the right side of preview to the right side of cell" },
	{ tThumbsY1,               L"Spacing in pixels from the top side of cell to the top side of preview" },
	{ tThumbsY2,               L"Spacing in pixels from the bottom side of preview to the bottom side of cell (text label is placed here)" },
	{ tTilesFontName,          L"Text labels font name in Tiles mode" },
	{ tTilesFontSize,          L"Text labels font height in Tiles mode" },
	{ tTilesImgSize,           L"Size in pixels of preview square in Tiles mode\r\nDefault is 48" },
	{ tTilesPadding,           L"Spacing in pixels on the right of text label" },
	{ tTilesSpacing,           L"Spacing in pixels on the left of text label" },
	{ tTilesX1,                L"Spacing in pixels from the left side of cell to the left side of preview" },
	{ tTilesX2,                L"Spacing in pixels from the right side of preview to the right side of cell (text label is placed here)" },
	{ tTilesY1,                L"Spacing in pixels from the top side of cell to the top side of preview" },
	{ tTilesY2,                L"Spacing in pixels from the bottom side of preview to the bottom side of cell" },
	{ tUpdateVerLocation,      L"URL to retrieve latest version information,\r\ndefault is: https://conemu.github.io/version.ini\r\nErase text box to revert to default URL." },
	{ tWndHeight,              L"Height of console window\r\nUse numbers for size in cells\r\nUse percent sign (e.g. ‘40%’) for monitor-relative size\r\nUse ‘px’ suffix (e.g. ‘800px’) for strict pixel size" },
	{ tWndWidth,               L"Width of console window\r\nUse numbers for size in cells\r\nUse percent sign (e.g. ‘40%’) for monitor-relative size\r\nUse ‘px’ suffix (e.g. ‘800px’) for strict pixel size" },
	{ tWndX,                   L"Upper left corner of ConEmu in Normal mode\r\nThis is in pixels" },
	{ tWndY,                   L"Upper left corner of ConEmu in Normal mode\r\nThis is in pixels" },
	{ vkAltEnter,              L"Full screen" },
	{ vkAltNumpad,             L"Start Alt+Number mode to enter unicode symbol by its hex codebase" },
	{ vkAlwaysOnTop,           L"Switch ‘Always on top’ window mode" },
	{ vkAppsBS,                L"Scroll buffer to the cursor position" },
	{ vkAppsEnd,               L"Scroll buffer to the bottom" },
	{ vkAppsHome,              L"Scroll buffer to the top" },
	{ vkAppsPgDn,              L"Scroll buffer one half-page down" },
	{ vkAppsPgUp,              L"Scroll buffer one half-page up" },
	{ vkCdExplorerPath,        L"Activate ConEmu and ‘CD’ to last (top in Z-order) Explorer window path" },
	{ vkChildSystemMenu,       L"Child GUI window system menu (PuTTY, Notepad, etc.)" },
	{ vkCloseAllCon,           L"Close all consoles" },
	{ vkCloseConEmu,           L"Close all tabs (same as ‘Cross’ click)" },
	{ vkCloseExceptCon,        L"Close all but active" },
	{ vkCloseGroup,            L"Close all panes of the active group" },
	{ vkCloseGroupPrc,         L"Close all active processes of the active group" },
	{ vkCloseTab,              L"Close current tab" },
	{ vkCloseZombies,          L"Close all zombies" },
	{ vkConDetach,             L"Detach active RealConsole from ConEmu" },
	{ vkConsole_1,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_10,            L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_2,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_3,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_4,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_5,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_6,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_7,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_8,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConsole_9,             L"Activate console by number (Use ‘Host-key’+Number to switch consoles)" },
	{ vkConUnfasten,           L"Unfasten active RealConsole from active ConEmu window" },
	{ vkCtrlDown,              L"Scroll buffer one line down (disabled in Far /w)" },
	{ vkCtrlPgDn,              L"Scroll buffer one page down (disabled in Far /w)" },
	{ vkCtrlPgUp,              L"Scroll buffer one page up (disabled in Far /w)" },
	{ vkCtrlShiftTab,          L"Previous tab (may be disabled)" },
	{ vkCtrlTab,               L"Next tab (may be disabled)" },
	{ vkCtrlTab_Down,          L"Switch tab to right (while Ctrl-Tab was pressed and Ctrl - hold)" },
	{ vkCtrlTab_Left,          L"Switch tab to left (while Ctrl-Tab was pressed and Ctrl - hold)" },
	{ vkCtrlTab_Right,         L"Switch tab to right (while Ctrl-Tab was pressed and Ctrl - hold)" },
	{ vkCtrlTab_Up,            L"Switch tab to left (while Ctrl-Tab was pressed and Ctrl - hold)" },
	{ vkCtrlUp,                L"Scroll buffer one line up (disabled in Far /w)" },
	{ vkCtrlWinAltSpace,       L"Show real console" },
	{ vkCtrlWinEnter,          L"Full screen" },
	{ vkCTSCopyHtml0,          L"Copy: Current selection as plain text" },
	{ vkCTSCopyHtml1,          L"Copy: Current selection HTML formatted" },
	{ vkCTSCopyHtml2,          L"Copy: Current selection as HTML" },
	{ vkCTSShiftDown,          L"Start block selection, ignored in Far, may be disabled on ‘Mark & Paste’ and ‘App distinct’ pages" },
	{ vkCTSShiftEnd,           L"Start text selection, ignored in Far, may be disabled on ‘Mark & Paste’ and ‘App distinct’ pages" },
	{ vkCTSShiftHome,          L"Start text selection, ignored in Far, may be disabled on ‘Mark & Paste’ and ‘App distinct’ pages" },
	{ vkCTSShiftLeft,          L"Start text selection, ignored in Far, may be disabled on ‘Mark & Paste’ and ‘App distinct’ pages" },
	{ vkCTSShiftRight,         L"Start text selection, ignored in Far, may be disabled on ‘Mark & Paste’ and ‘App distinct’ pages" },
	{ vkCTSShiftUp,            L"Start block selection, ignored in Far, may be disabled on ‘Mark & Paste’ and ‘App distinct’ pages" },
	{ vkCTSVkAct,              L"Right and middle mouse buttons modifier (Text selection)" },
	{ vkCTSVkBlock,            L"Block selection modifier" },
	{ vkCTSVkBlockStart,       L"Start vertical block selection (like standard console)" },
	{ vkCTSVkCopyAll,          L"Copy: All active console text output (buffer including)" },
	{ vkCTSVkPromptClk,        L"Change prompt text cursor position with left mouse click (cmd, powershell, tcc/le, ...)" },
	{ vkCTSVkText,             L"Text selection modifier" },
	{ vkCTSVkTextStart,        L"Start text selection (like text editors)" },
	{ vkDebugProcess,          L"Debug active process" },
	{ vkDeleteLeftWord,        L"Delete word leftward to the cursor (ignored in Far)" },
	{ vkDumpProcess,           L"Active process memory dump" },
	{ vkDumpTree,              L"Active process tree memory dump" },
	{ vkDuplicateRoot,         L"Duplicate tab with current state of root process" },
	{ vkDuplicateRootAs,       L"Duplicate tab with current state of root process, run ‘As Administrator’" },
	{ vkEscNoConsoles,         L"Minimize ConEmu by Esc when no open consoles left (see option ‘Don't close ConEmu on last console close’)" },
	{ vkFarGotoEditorVk,       L"Highlighting: hyperlinks and compiler errors (FarGotoEditor modifier)" },
	{ vkFindTextDlg,           L"Find text in active console" },
	{ vkFontLarger,            L"Make main font larger" },
	{ vkFontOriginal,          L"Make main font original size" },
	{ vkFontSmaller,           L"Make main font smaller" },
	{ vkForceFullScreen,       L"Enter TEXT fullscreen mode, when available. If not - standard fullscreen and always on top" },
	{ vkGlobalRestore,         L"Restore (bring to front)" },
	{ vkHighlightMouse,        L"Highlighting: Switch ‘Highlight row under mouse cursor’" },
	{ vkHighlightMouseX,       L"Highlighting: Switch ‘Highlight row & col under mouse cursor’" },
	{ vkJumpActiveMonitor,     L"Move ConEmu window to the monitor with mouse cursor (Bring here)" },
	{ vkJumpNextMonitor,       L"Move ConEmu window to next monitor" },
	{ vkJumpPrevMonitor,       L"Move ConEmu window to previous monitor" },
	{ vkLDragKey,              L"Drag from Far panels with left mouse key (LDrag modifier)" },
	{ vkMaximize,              L"Maximize/restore" },
	{ vkMaximizeHeight,        L"Snap ConEmu window to the monitor's top/bottom edges (maximize height)" },
	{ vkMaximizePane,          L"Split: Maximize/restore active pane" },
	{ vkMaximizeWidth,         L"Snap ConEmu window to the monitor's left/right edges (maximize width)" },
	{ vkMinimizeRestor2,       L"Minimize/Restore (alternative)" },
	{ vkMinimizeRestore,       L"Minimize/Restore (Quake-style hotkey also)" },
	{ vkMoveTabLeft,           L"Move active tab leftward" },
	{ vkMoveTabRight,          L"Move active tab rightward" },
	{ vkMultiAltCon,           L"Show alternative console buffer (last command output)" },
	{ vkMultiBuffer,           L"Switch bufferheight mode" },
	{ vkMultiClose,            L"Close active console" },
	{ vkMultiCmd,              L"Create new ‘cmd.exe’ console" },
	{ vkMultiGroup,            L"Group keyboard input for visible splits" },
	{ vkMultiNew,              L"Create new console or new window (check ‘Multiple consoles in one ConEmu window’)" },
	{ vkMultiNewAttach,        L"Attach existing Console or GUI application" },
	{ vkMultiNewPopup,         L"Show create new console popup menu" },
	{ vkMultiNewPopup2,        L"Show create new console popup menu with task submenus" },
	{ vkMultiNewShift,         L"Create new console (after ‘Create confirmation’)" },
	{ vkMultiNewWnd,           L"Create new window (after ‘Create confirmation’)" },
	{ vkMultiNext,             L"Switch next console" },
	{ vkMultiNextShift,        L"Switch previous console" },
	{ vkMultiPause,            L"Pause current console" },
	{ vkMultiRecreate,         L"Recreate active console" },
	{ vkPasteCygwin,           L"Paste path from clipboard in unix format" },
	{ vkPasteDirectory,        L"Choose and paste folder path" },
	{ vkPasteFilePath,         L"Choose and paste file pathname" },
	{ vkPasteFirstLine,        L"Paste first line of clipboard contents, autoconvert paths for cygwin's applications (ignored in Far)" },
	{ vkPasteText,             L"Paste clipboard contents (ignored in Far)" },
	{ vkPicViewFaster,         L"PicView Far plugin: Slideshow faster" },
	{ vkPicViewSlide,          L"PicView Far plugin: Slideshow start" },
	{ vkPicViewSlower,         L"PicView Far plugin: Slideshow slower" },
	{ vkRDragKey,              L"Drag from Far panels with right mouse key (RDrag modifier)" },
	{ vkRenameTab,             L"Rename active tab" },
	{ vkResetTerminal,         L"Reset terminal: clear screen, backscroll, move cursor to the upper-left corner" },
	{ vkScreenshot,            L"Make screenshot of active window" },
	{ vkScreenshotFull,        L"Make screenshot of entire desktop" },
	{ vkSetFocusChild,         L"Set focus to child GUI application" },
	{ vkSetFocusGui,           L"Set focus to ConEmu" },
	{ vkSetFocusSwitch,        L"Switch focus between ConEmu and child GUI application (e.g. PuTTY or Notepad)" },
	{ vkShowCaption,           L"Show window caption" },
	{ vkShowStatusBar,         L"Show status bar" },
	{ vkShowTabBar,            L"Show tab bar" },
	{ vkShowTabsList,          L"Show opened tabs list (ignored in Far - use macro instead)" },
	{ vkShowTabsList2,         L"Show opened tabs list (works in Far too)" },
	{ vkSplitFocusDown,        L"Split: Put focus to nearest pane downward" },
	{ vkSplitFocusLeft,        L"Split: Put focus to nearest pane leftward" },
	{ vkSplitFocusRight,       L"Split: Put focus to nearest pane rightward" },
	{ vkSplitFocusUp,          L"Split: Put focus to nearest pane upward" },
	{ vkSplitNewConH,          L"Split: Duplicate active ‘shell’ split to right" },
	{ vkSplitNewConV,          L"Split: Duplicate active ‘shell’ split to bottom" },
	{ vkSplitSizeHleft,        L"Split: Move splitter leftward" },
	{ vkSplitSizeHright,       L"Split: Move splitter rightward" },
	{ vkSplitSizeVdown,        L"Split: Move splitter downward" },
	{ vkSplitSizeVup,          L"Split: Move splitter upward" },
	{ vkSystemMenu,            L"Show ConEmu System menu" },
	{ vkSystemMenu2,           L"Show ConEmu System menu" },
	{ vkTabMenu,               L"Show Tab context menu" },
	{ vkTabMenu2,              L"Show Tab context menu" },
	{ vkTabPane,               L"Split: Put focus to next visible pane" },
	{ vkTabPaneShift,          L"Split: Put focus to previous visible pane" },
	{ vkTermButShell,          L"Terminate all but shell processes in the current console" },
	{ vkTerminateApp,          L"Terminate active process in the current console" },
	{ vkTileToLeft,            L"Snap ConEmu window to the monitor's left edge" },
	{ vkTileToRight,           L"Snap ConEmu window to the monitor's right edge" },
	{ vkTransparencyDec,       L"Transparency: more opaque" },
	{ vkTransparencyInc,       L"Transparency: more translucent" },
	{ vkWinAltA,               L"Show ‘About’ dialog" },
	{ vkWinAltH,               L"Open online help/wiki in your browser" },
	{ vkWinAltK,               L"Setup ‘Hotkeys’" },
	{ vkWinAltP,               L"Settings dialog" },
	{ vkWinAltSpace,           L"Show ConEmu menu" },
	{ vkWinAltT,               L"Setup ‘Tasks’" },
	{ vkWinDown,               L"Increase window height (check ‘Resize with arrows’)" },
	{ vkWinLeft,               L"Decrease window width (check ‘Resize with arrows’)" },
	{ vkWinRight,              L"Increase window width (check ‘Resize with arrows’)" },
	{ vkWinUp,                 L"Decrease window height (check ‘Resize with arrows’)" },
	{ vkWndDragKey,            L"Move ConEmu window by dragging client area" },
	{ /* empty trailing item for patch convenience */ }
};
