//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ConEmu.rc
//
#define IDI_ICON1                       1
#define IDI_ICON2                       2
#define IDI_ICON3                       3
#define ID_GO                           20
#define ID_ATTACH                       21
#define IDB_MAIN_TOOLBAR                101
#define IDB_SHIELD                      102
#define IDB_RIGHTCLICKING               103
#define IDB_SCROLL                      104
#define IDB_SHIELD16                    107
#define IDB_SEARCH                      108
#define IDB_DONATE                      109
#define IDB_FLATTR                      110
#define IDC_COPY                        120
#define IDC_LINK                        121
#define IDC_MOVE                        122
#define IDD_RESTART                     123
#define IDC_SPLITV                      124
#define IDC_SPLITH                      125
#define IDD_SETTINGS                    150
#define IDD_SPG_FONTS                   151
#define IDD_SPG_COLORS                  152
#define IDD_SPG_INFO                    153
#define IDD_SPG_FEATURES                154
#define IDD_SPG_DEBUG                   155
#define IDD_SPG_FEATURE_FAR             156
#define IDD_SPG_TASKS                   157
#define IDD_SPG_APPDISTINCT             158
#define IDD_SPG_COMSPEC                 159
#define IDD_SPG_STARTUP                 160
#define IDD_SPG_STATUSBAR               161
#define IDD_SPG_APPDISTINCT2            162
#define IDD_SPG_CURSOR                  163
#define IDD_SPG_INTEGRATION             164
#define IDD_SPG_TRANSPARENT             165
#define IDD_SPG_SIZEPOS                 167
#define IDD_SPG_MARKCOPY                168
#define IDD_SPG_TABS                    169
#define IDD_SPG_VIEWS                   170
#define IDD_SPG_KEYS                    171
#define IDD_SPG_UPDATE                  172
#define IDD_SPG_APPEAR                  174
#define IDD_SPG_TASKBAR                 175
#define IDD_SPG_DEFTERM                 176
#define IDD_SPG_FARMACRO                177
#define IDD_SPG_HIGHLIGHT               178
#define IDD_SPG_PASTE                   179
#define IDD_SPG_CONFIRM                 180
#define IDD_SPG_HISTORY                 181
#define IDD_SPG_BACKGR                  182
#define IDD_SPG_ENVIRONMENT             183
#define IDD_SPG_KEYBOARD                184
#define IDD_SPG_MOUSE                   185
#define IDD_SPG_QUAKE                   186
#define IDD_SPG_CHILDGUI                187
#define IDD_SPG_ANSI                    188
#define IDD_MORE_CONFONT                209
#define IDD_MORE_DOSBOX                 210
#define IDD_ATTACHDLG                   212
#define IDD_FAST_CONFIG                 215
#define IDD_FIND                        217
#define IDD_ABOUT                       218
#define IDD_RENAMETAB                   219
#define IDD_CMDPROMPT                   220
#define IDD_HELP                        221
#define IDD_ACTION                      222
#define IDD_HOTKEY                      223
#define IDD_AFFINITY                    226
#define c0                              1000
#define c1                              1001
#define c2                              1002
#define c3                              1003
#define c4                              1004
#define c5                              1005
#define c6                              1006
#define c7                              1007
#define c8                              1008
#define c9                              1009
#define c10                             1010
#define c11                             1011
#define c12                             1012
#define c13                             1013
#define c14                             1014
#define c15                             1015
#define c16                             1016
#define c17                             1017
#define c18                             1018
#define c19                             1019
#define c20                             1020
#define c21                             1021
#define c22                             1022
#define c23                             1023
#define c24                             1024
#define c25                             1025
#define c26                             1026
#define c27                             1027
#define c28                             1028
#define c29                             1029
#define c30                             1030
#define c31                             1031
#define c32                             1032
#define c33                             1033
#define c34                             1034
#define c35                             1035
#define c36                             1036
#define c37                             1037
#define c38                             1038
#define tc0                             1100
#define tc1                             1101
#define tc2                             1102
#define tc3                             1103
#define tc4                             1104
#define tc5                             1105
#define tc6                             1106
#define tc7                             1107
#define tc8                             1108
#define tc9                             1109
#define tc10                            1110
#define tc11                            1111
#define tc12                            1112
#define tc13                            1113
#define tc14                            1114
#define tc15                            1115
#define tc16                            1116
#define tc17                            1117
#define tc18                            1118
#define tc19                            1119
#define tc20                            1120
#define tc21                            1121
#define tc22                            1122
#define tc23                            1123
#define tc24                            1124
#define tc25                            1125
#define tc26                            1126
#define tc27                            1127
#define tc28                            1128
#define tc29                            1129
#define tc30                            1130
#define tc31                            1131
#define tc32                            1132
#define tc33                            1133
#define tc34                            1134
#define tc35                            1135
#define tc36                            1136
#define tc37                            1137
#define tc38                            1138
#define bChooseFont                     1201
#define rNoneAA                         1202
#define rStandardAA                     1203
#define rCTAA                           1204
#define cbFullScreen                    1205
#define tFont                           1206
#define cbFixFarBorders                 1207
#define cbCursorColor                   1210
#define rNormal                         1311
#define rMaximized                      1312
#define rFullScreen                     1313
#define gbPerformance                   1400
#define lbLDragKey                      1501
#define cbDropEnabled                   1502
#define lbRDragKey                      1503
#define cbDragL                         1504
#define cbDragR                         1505
#define cbMultiCon                      1506
#define cbMinToTray                     1507
#define tCurCmdLine                     1508
#define tsTopPID                        1510
#define tFontFace                       1511
#define tFontSizeY                      1512
#define tFontCharset                    1513
#define tFontFace2                      1514
#define cbExtendColors                  1515
#define tCmdLine                        1516
#define tRealFontMain                   1517
#define tRealFontBorders                1518
#define cbApplyPos                      1520
#define cbCursorBlink                   1522
#define IDC_RESTART_ICON                1523
#define IDC_START                       1524
#define IDC_TERMINATE                   1525
#define IDC_RESTART_CMD                 1527
#define IDC_CHOOSE                      1528
#define gbStartCommand                  1529
#define IDC_WARNING                     1530
#define cbTabSelf                       1531
#define cbTabLazy                       1532
#define cbTabRecent                     1533
#define cbLongOutput                    1534
#define tLongOutputHeight               1535
#define cbRSelectionFix                 1536
#define cbMonitorConsoleLang            1537
#define cbSkipFocusEvents               1538
#define cbSkipActivation                1542
#define cbSkipMove                      1543
#define gbStandardColors                1544
#define cbVisible                       1545
#define cbNewConfirm                    1546
#define cbRunAsAdmin                    1547
#define cbDragImage                     1548
#define cbAutoRegFonts                  1550
#define cbDebugSteps                    1551
#define cbDragIcons                     1553
#define lbDefaultColors                 1554
#define lbCmdOutputCP                   1558
#define lbNtvdmHeight                   1559
#define IDC_CONSOLE_STATES              1560
#define cbFARuseASCIIsort               1561
#define cbFixAltOnAltTab                1562
#define cbFarHourglass                  1563
#define slTransparent                   1564
#define cbHideCaption                   1565
#define cbFontAuto                      1566
#define cbDragPanel                     1568
#define cbHideCaptionAlways             1569
#define cbTryToCenter                   1570
#define cbAlwaysOnTop                   1572
#define cbUserScreenTransparent         1573
#define cbTransparent                   1574
#define tBgImageColors                  1575
#define cbExtendFonts                   1576
#define lbExtendFontBoldIdx             1577
#define cbTrueColorer                   1578
#define cbDropUnlocked                  1579
#define cbDropUseBCopy                  1580
#define cbFadeInactive                  1581
#define tHideCaptionAlwaysFrame         1589
#define tHideCaptionAlwaysDelay         1590
#define tHideCaptionAlwaysDissapear     1591
#define bMultiConHotkeys                1592
#define cbMultiConKeybHooks             1593
#define bTabTemplates                   1594
#define bResetSettings                  1595
#define bReloadSettings                 1596
#define tConSizeChr                     1597
#define tConSizePix                     1598
#define tDCSize                         1599
#define tPanelLeft                      1600
#define tPanelRight                     1601
#define IDC_CHOOSE_DIR                  1602
#define IDC_STARTUP_DIR                 1603
#define bRClick                         1607
#define bRealConsoleSettings            1608
#define bDropSettings                   1609
#define bSaveSettings                   1610
#define cbHandleFarDetach               1619
#define tCursorPos                      1622
#define tFadeLow                        1624
#define tFadeHigh                       1625
#define cbToolbar                       1626
#define cbCTSTextSelection              1630
#define lbCTSMBtnAction                 1631
#define lbCTSRBtnAction                 1632
#define lbCTSBlockSelection             1633
#define lbCTSTextSelection              1634
#define cbCTSBlockSelection             1635
#define lbCTSForeIdx                    1636
#define lbCTSBackIdx                    1637
#define tTabConsole                     1638
#define tTabEditor                      1639
#define tTabViewer                      1640
#define tTabEditorMod                   1641
#define cbHideInactiveConTabs           1642
#define tTabLenMax                      1643
#define tTabPanels                      1644
#define lbCTSActAlways                  1645
#define tAdminSuffix                    1647
#define cbUseWinNumber                  1648
#define cbInstallKeybHooks              1649
#define cbRunAsRestricted               1650
#define cbRunAsNetOnly                  1651
#define tRunAsUser                      1652
#define tRunAsPassword                  1653
#define cbSafeFarClose                  1654
#define cbCursorIgnoreSize              1655
#define rbCurrentUser                   1656
#define rbAnotherUser                   1657
#define tThumbsFontName                 1659
#define tThumbsFontSize                 1660
#define tTilesFontName                  1661
#define tThumbMaxZoom                   1662
#define cbThumbLoadFolders              1663
#define cbThumbLoadFiles                1664
#define tThumbFullSize                  1665
#define tTilesFontSize                  1666
#define cbThumbPreviewBox               1667
#define cbThumbSelectionBox             1668
#define tThumbLabelHeight               1669
#define rbThumbBackColorIdx             1670
#define rbThumbBackColorRGB             1671
#define lbThumbBackColorIdx             1672
#define rbThumbPreviewBoxColorIdx       1673
#define rbThumbPreviewBoxColorRGB       1674
#define lbThumbPreviewBoxColorIdx       1675
#define rbThumbSelectionBoxColorIdx     1676
#define rbThumbSelectionBoxColorRGB     1677
#define lbThumbSelectionBoxColorIdx     1678
#define tThumbLoadingTimeout            1679
#define cbThumbUsePicView2              1680
#define tTilesImgSize                   1681
#define tThumbsImgSize                  1682
#define rbThumbCachePluginFolder        1687
#define rbThumbCacheUserFolder          1688
#define rbThumbCacheDisabled            1689
#define rbThumbCacheSpecifiedFolder     1690
#define cbThumbCacheFolder              1691
#define tThumbCacheFolder               1692
#define cbRClick                        1696
#define tBgImage                        1697
#define tDarker                         1698
#define cbBgImage                       1699
#define tThumbSupportedExtensions       1700
#define cbTilesPreviewBox               1701
#define cbTilesSelectionBox             1702
#define tThumbsX1                       1703
#define tThumbsY1                       1704
#define tThumbsX2                       1705
#define tThumbsY2                       1706
#define tThumbsSpacing                  1707
#define tThumbsPadding                  1708
#define tTilesX1                        1709
#define tTilesY1                        1710
#define tTilesX2                        1711
#define tTilesY2                        1712
#define tTilesSpacing                   1713
#define tTilesPadding                   1714
#define bApplyViewSettings              1715
#define bConFontOK                      1716
#define cbActivityReset                 1717
#define cbDisableFarFlashing            1718
#define cbDisableAllFlashing            1719
#define cbThumbRestoreOnStartup         1720
#define cbSleepInBackground             1721
#define cbExtendUCharMap                1722
#define cbAutoSaveSizePos               1723
#define bDosBoxSettings                 1724
#define cbShellNoZoneCheck              1725
#define bConFontCancel                  1726
#define tConsoleFontFace                1727
#define tConsoleFontSizeY               1728
#define tConsoleFontSizeX               1729
#define bConFontAdd2HKLM                1730
#define tConsoleFontHklmNote            1731
#define tConsoleFontConsoleNote         1732
#define cbBgAllowPlugin                 1734
#define cbTabsInCaption                 1735
#define cbAlwaysShowTrayIcon            1736
#define cbLogShellActivity              1740
#define cbLogInputActivity              1741
#define lbActivityLog                   1742
#define gbActivityLog                   1744
#define cbActivitySaveAs                1746
#define rbActivityDisabled              1747
#define rbActivityShell                 1748
#define ebActivityApp                   1750
#define ebActivityParm                  1751
#define cbUseInjects                    1752
#define cbDosBox                        1753
#define ebDosBoxPath                    1754
#define bDosBoxPath                     1755
#define ebDosBoxForceConfig             1756
#define bDosBoxForceConfig              1757
#define ebDosBoxDrives                  1758
#define ebDosBoxAutoexec                1759
#define tsRConFlags                     1760
#define rbActivityInput                 1762
#define cbUseWinTab                     1764
#define cbFarGotoEditor                 1765
#define lbFarGotoEditorVk               1766
#define hkHotKeySelect                  1767
#define cbUseWinArrows                  1768
#define stHotKeySelect                  1769
#define stHotModifierSelect             1770
#define lbConEmuHotKeys                 1771
#define IDC_ATTACHLIST                  1774
#define IDC_REFRESH                     1776
#define cbSendAltTab                    1777
#define cbSendAltEsc                    1778
#define cbSendAltPrintScrn              1779
#define cbSendPrintScrn                 1780
#define cbSendCtrlEsc                   1781
#define cbDosBoxForceConfig             1783
#define vkMinimizeRestore               2000
#define vkMultiNew                      2001
#define vkMultiNext                     2002
#define vkMultiRecreate                 2003
#define vkMultiBuffer                   2004
#define vkMultiClose                    2005
#define vkMultiCmd                      2006
#define vkCTSVkBlock                    2007
#define vkCTSVkText                     2008
#define vkCTSVkAct                      2009
#define vkFarGotoEditorVk               2010
#define vkLDragKey                      2011
#define vkRDragKey                      2012
#define vkWinAltP                       2013
#define vkWinAltSpace                   2014
#define vkMaximize                      2015
#define vkCtrlWinAltSpace               2016
#define vkAltEnter                      2017
#define vkSystemMenu                    2018
#define vkCtrlUp                        2019
#define vkCtrlDown                      2020
#define vkCtrlPgUp                      2021
#define vkCtrlPgDn                      2022
#define vkCtrlTab                       2023
#define vkCtrlShiftTab                  2024
#define vkCtrlTab_Left                  2025
#define vkCtrlTab_Right                 2026
#define vkCtrlTab_Up                    2027
#define vkCtrlTab_Down                  2028
#define vkCtrlWinEnter                  2029
#define vkMultiNextShift                2030
#define vkConsole_1                     2031
#define vkConsole_2                     2032
#define vkConsole_3                     2033
#define vkConsole_4                     2034
#define vkConsole_5                     2035
#define vkConsole_6                     2036
#define vkConsole_7                     2037
#define vkConsole_8                     2038
#define vkConsole_9                     2039
#define vkConsole_10                    2040
#define vkConsole_11                    2041
#define vkConsole_12                    2042
#define vkMultiNewShift                 2043
#define vkWinLeft                       2044
#define vkWinRight                      2045
#define vkWinUp                         2046
#define vkWinDown                       2047
#define cbTabsOnTaskBar                 2048
#define tvSetupCategories               2049
#define tSetupPagePlace                 2050
#define tUpdateVerLocation              2052
#define cbShowFarWindows                2053
#define rbUpdateStableOnly              2054
#define rbUpdatePreview                 2055
#define rbUpdateLatestAvailable         2056
#define cbUpdateCheckOnStartup          2058
#define cbUpdateUseProxy                2059
#define tUpdateProxy                    2060
#define tUpdateProxyUser                2061
#define tUpdateProxyPassword            2062
#define tUpdateDownloadPath             2063
#define cbUpdateDownloadPath            2064
#define cbUpdateLeavePackages           2065
#define tUpdatePostUpdateCmd            2066
#define cbUpdateCheckHourly             2067
#define cbUpdateConfirmDownload         2068
#define rbActivityComm                  2069
#define rbUpdateUseExe                  2070
#define rbUpdateUseArc                  2071
#define tUpdateArcCmdLine               2072
#define cbUpdateArcCmdLine              2073
#define tUpdateExeCmdLine               2074
#define tRClickMacro                    2075
#define cbEnhanceButtons                2076
#define tCloseTabMacro                  2078
#define tSaveAllMacro                   2079
#define tSafeFarCloseMacro              2080
#define stUpdateProxy                   2083
#define stUpdateProxyUser               2084
#define stUpdateProxyPassword           2085
#define cbUseKeyboardHooksFast          2086
#define cbEnableAutoUpdateFast          2087
#define cbDisableConImeFast             2090
#define stEnableAutoUpdateFast          2093
#define stDisableConImeFast1            2094
#define stDisableConImeFast2            2095
#define stDisableConImeFast3            2096
#define gbDisableConImeFast             2097
#define cbInjectConEmuHkFast            2098
#define lbHotKeyList                    2101
#define cbDragPanelBothEdges            2102
#define stHomePage                      2103
#define cbMultiIterate                  2104
#define tGuiMacro                       2105
#define tTabFontFace                    2106
#define tTabFontHeight                  2107
#define tTabFontCharset                 2108
#define cbAdminShield                   2109
#define cbAdminSuffix                   2110
#define vkTabMenu                       2111
#define vkCTSVkBlockStart               2112
#define vkCTSVkTextStart                2113
#define cbKeyBarRClick                  2114
#define gbCmdTasks                      2115
#define lbCmdTasks                      2116
#define tCmdGroupName                   2117
#define tCmdGroupCommands               2118
#define stCmdTasks                      2119
#define stCmdGroupName                  2120
#define stCmdGroupCommands              2121
#define cbCmdTasksAdd                   2122
#define cbColorSchemeSave               2123
#define cbCmdTasksDel                   2124
#define cbColorSchemeDelete             2125
#define cbCmdTasksUp                    2126
#define cbCmdTasksDown                  2127
#define cbCmdGroupApp                   2128
#define cbCmdTasksParm                  2129
#define cbCmdTasksSave                  2130
#define cbCmdTasksReload                2131
#define cbCmdTaskbarTasks               2132
#define cbCmdTaskbarCommands            2133
#define gbCmdTasks7                     2134
#define tAppDistinctName                2135
#define cbAppDistinctAdd                2136
#define cbAppDistinctDel                2137
#define cbAppDistinctUp                 2138
#define cbAppDistinctDown               2139
#define cbAppDistinctReload             2140
#define rbAppDistinctElevatedOn         2141
#define rbAppDistinctElevatedOff        2142
#define rbAppDistinctElevatedIgnore     2143
#define cbExtendFontsOverride           2144
#define cbCursorOverride                2145
#define cbColorsOverride                2146
#define lbColorsOverride                2147
#define rbComspecAuto                   2148
#define rbComspecEnvVar                 2149
#define rbComspecCmd                    2150
#define rbComspecExplicit               2151
#define tComspecExplicit                2152
#define cbComspecExplicit               2153
#define gbCmdRun                        2154
#define gbComspec                       2155
#define gbComspecBits                   2156
#define rbComspec_OSbit                 2157
#define rbComspec_AppBit                2158
#define rbComspec_x32                   2159
#define cbComspecUpdateEnv              2160
#define cbComspecTest                   2162
#define gbFeatureMisc                   2163
#define gbFeatureAppear                 2164
#define gbFeatureCaption                2165
#define gbFeatureClipboard              2166
#define cbClipConfirmEnter              2171
#define cbClipboardOverride             2172
#define tFindText                       2173
#define cbFindWholeWords                2174
#define cbFindMatchCase                 2175
#define cbFindFreezeConsole             2176
#define cbFindNext                      2177
#define cbFindPrev                      2178
#define cbCloseConsoleConfirm           2179
#define gbKeyModifiers                  2180
#define vkPicViewSlide                  2181
#define vkPicViewSlower                 2182
#define vkPicViewFaster                 2183
#define lbHotKeyMod1                    2186
#define lbHotKeyMod2                    2187
#define lbHotKeyMod3                    2188
#define stGuiMacro                      2189
#define vkGuiMacro01                    2190
#define vkGuiMacro02                    2191
#define vkGuiMacro03                    2192
#define vkGuiMacro04                    2193
#define vkGuiMacro05                    2194
#define vkGuiMacro06                    2195
#define vkGuiMacro07                    2196
#define vkGuiMacro08                    2197
#define vkGuiMacro09                    2198
#define vkGuiMacro10                    2199
#define vkGuiMacro11                    2200
#define vkGuiMacro12                    2201
#define vkGuiMacro13                    2202
#define vkGuiMacro14                    2203
#define vkGuiMacro15                    2204
#define vkGuiMacro16                    2205
#define vkGuiMacro17                    2206
#define vkGuiMacro18                    2207
#define vkGuiMacro19                    2208
#define vkGuiMacro20                    2209
#define vkGuiMacro21                    2210
#define vkGuiMacro22                    2211
#define vkGuiMacro23                    2212
#define vkGuiMacro24                    2213
#define vkGuiMacro25                    2214
#define vkGuiMacro26                    2215
#define vkGuiMacro27                    2216
#define vkGuiMacro28                    2217
#define vkGuiMacro29                    2218
#define vkGuiMacro30                    2219
#define vkGuiMacro31                    2220
#define vkGuiMacro32                    2221
#define vkShowTabsList                  2222
#define vkPasteText                     2223
#define vkPasteFirstLine                2224
#define cbClipConfirmLimit              2225
#define tClipConfirmLimit               2226
#define stClipConfirmLimit              2227
#define cbFindHighlightAll              2228
#define gbFindText                      2229
#define vkFindTextDlg                   2230
#define cbFindTransparent               2232
#define rbStartSingleApp                2233
#define rbStartTasksFile                2234
#define rbStartNamedTask                2235
#define rbStartLastTabs                 2236
#define cbStartFarRestoreFolders        2237
#define cbStartFarRestoreEditors        2238
#define tStartTasksFile                 2239
#define lbStartNamedTask                2240
#define stExtendFontBoldIdx             2241
#define stExtendFontItalicIdx           2242
#define stExtendFontNormalIdx           2243
#define cbCmdLine                       2244
#define cbStartTasksFile                2245
#define cbDropUseMenu                   2246
#define stConEmuIcon                    2247
#define tbAboutTabs                     2248
#define tAboutText                      2249
#define stConEmuAbout                   2250
#define stConEmuUrl                     2251
#define vkMultiNewPopup                 2252
#define cbProcessAnsi                   2253
#define vkMultiAltCon                   2254
#define lbGotoEditorCmd                 2255
#define stGotoEditorCmd                 2256
#define cbCTSFreezeBeforeSelect         2257
#define bGotoEditorCmd                  2259
#define vkForceFullScreen               2260
#define vkTerminateApp                  2261
#define cbShowStatusBar                 2262
#define cbStatusActiveVCon              2263
#define cbStatusWindowPos               2264
#define cbStatusWindowSize              2265
#define cbStatusActiveBuffer            2266
#define cbStatusConsolePos              2267
#define cbStatusConsoleSize             2268
#define cbStatusBufferSize              2269
#define cbStatusCursorX                 2270
#define cbStatusCursorY                 2271
#define cbStatusCursorSize              2272
#define cbStatusCursorInfo              2273
#define cbStatusServer                  2274
#define tStatusFontFace                 2275
#define tStatusFontHeight               2276
#define tStatusFontCharset              2277
#define cbBold                          2278
#define tFontSizeX                      2279
#define cbItalic                        2280
#define tWndWidth                       2281
#define tWndHeight                      2282
#define cbMonospace                     2283
#define tFontSizeX2                     2284
#define slDarker                        2285
#define cbDnDCopy                       2287
#define cbTabs                          2288
#define cbEnhanceGraphics               2289
#define tFontSizeX3                     2290
#define bBgImage                        2291
#define tWndX                           2295
#define tWndY                           2296
#define cbPosFixed                      2297
#define tabMain                         2298
#define lbExtendIdx                     2299
#define lbExtendFontItalicIdx           2300
#define lbExtendFontNormalIdx           2301
#define rCascade                        2302
#define rFixed                          2303
#define lbProcesses                     2304
#define cbStatusWindowClient            2305
#define cbStatusWindowWorkspace         2306
#define cbStatusCapsLock                2307
#define cbStatusTransparency            2308
#define cbStatusNumLock                 2309
#define cbStatusScrlLock                2310
#define cbStatusInputLang               2311
#define cbColorKeyTransparent           2312
#define cbEnableMouse                   2313
#define vkMultiNewAttach                2314
#define vkScreenshot                    2315
#define tTabSkipWords                   2316
#define gbAppDistinct                   2317
#define lbAppDistinct                   2318
#define stAppDistinctName               2319
#define cbCmdTaskbarUpdate              2320
#define cbStatusGuiPID                  2321
#define tCmdGroupGuiArg                 2322
#define stCmdGroupGuiArg                2323
#define vkWinAltA                       2324
#define vkShowStatusBar                 2325
#define vkShowTabBar                    2326
#define vkAlwaysOnTop                   2327
#define vkScreenshotFull                2328
#define vkMultiNewWnd                   2329
#define cbRunInNewWindow                2330
#define cbQuakeStyle                    2333
#define cbGuiMacroHelp                  2334
#define vkRenameTab                     2335
#define stNewTabName                    2336
#define tNewTabName                     2337
#define stBgPlacement                   2338
#define lbBgPlacement                   2339
#define cbCTSAutoCopy                   2340
#define cbStatusGuiHwnd                 2341
#define cbStatusViewHwnd                2342
#define cbStatusRealHwnd                2343
#define cbCTSClickPromptPosition        2344
#define lbCTSClickPromptPosition        2345
#define vkCTSVkPromptClk                2346
#define gbPromptOverride                2347
#define gbCopyingOverride               2348
#define tAppDistinctHolder              2353
#define tScrollAppearDelay              2354
#define tScrollDisappearDelay           2355
#define tPadSize                        2356
#define stAppDistinctBottom             2357
#define cbCTSDetectLineEnd              2358
#define cbCTSBashMargin                 2359
#define cbCTSTrimTrailing               2365
#define stCTSEOL                        2366
#define lbCTSEOL                        2367
#define tCursorFixedSize                2368
#define stCursorFixedSize               2369
#define tCursorMinSize                  2370
#define stCursorMinSize                 2371
#define lbHistoryList                   2372
#define tHistoryEdit                    2373
#define stHistoryList                   2374
#define stHistoryEdit                   2375
#define cbHistoryDontClose              2376
#define cbHistoryAutoExecute            2377
#define cbHistoryTopMost                2378
#define slTransparentInactive           2380
#define cbTransparentSeparate           2381
#define stTransparentInactive           2382
#define stOpaqueInactive                2383
#define tInsideIcon                     2384
#define tInsideConfig                   2385
#define tInsideShell                    2386
#define bInsideRegister                 2387
#define bInsideUnregister               2388
#define tHereIcon                       2389
#define tHereConfig                     2390
#define tHereShell                      2391
#define bHereRegister                   2392
#define bHereUnregister                 2393
#define tCmdAutoAttach                  2394
#define bCmdAutoRegister                2395
#define bCmdAutoUnregister              2396
#define cbInsideSyncDir                 2397
#define lbConClrText                    2398
#define lbConClrBack                    2399
#define lbConClrPopText                 2401
#define lbConClrPopBack                 2402
#define cbSnapToDesktopEdges            2403
#define vkWndDragKey                    2404
#define IDC_ATTACH_ALT                  2405
#define cbInsideName                    2406
#define cbHereName                      2407
#define cbCmdAutorunNewWnd              2411
#define cbCTSEndOnTyping                2412
#define vkMinimizeRestor2               2413
#define vkMoveTabLeft                   2414
#define vkMoveTabRight                  2415
#define cbStatusNewVCon                 2416
#define cbUseCurrentSizePos             2417
#define cbUseClink                      2418
#define cbStatusActiveProcess           2419
#define cbStatusConsoleTitle            2420
#define cbStatusVertSep                 2421
#define cbStatusHorzSep                 2422
#define cbAddConEmu2Path                2423
#define bCmdAutoClear                   2424
#define tDarkerPlugin                   2427
#define slDarkerPlugin                  2428
#define cbShowWasHiddenMsg              2435
#define cbCTSEndOnKeyPress              2436
#define vkShowCaption                   2437
#define stWndWidth                      2438
#define stWndHeight                     2439
#define gbRecreateSplit                 2440
#define rbRecreateSplitNone             2441
#define rbRecreateSplit2Right           2442
#define rbRecreateSplit2Bottom          2443
#define tRecreateSplit                  2444
#define stRecreateSplit                 2445
#define cbComspecUncPaths               2451
#define cbCmdTasksDir                   2452
#define vkFontLarger                    2453
#define vkFontSmaller                   2454
#define vkShowTabsList2                 2455
#define cbClipStartBlockSelection       2458
#define cbClipStartTextSelection        2459
#define lbClipStartBlockSelection       2460
#define lbClipStartTextSelection        2461
#define cbQuakeAutoHide                 2466
#define cbFullscreenNoBars              2468
#define cbFullscreenFixedConSize        2469
#define tFullScreenWidth                2470
#define tFullScreenHeight               2471
#define rbTaskbarBtnActive              2472
#define rbTaskbarBtnAll                 2473
#define rbTaskbarBtnWin7                2474
#define rbTaskbarBtnHidden              2475
#define rbTabsAlways                    2476
#define rbTabsAuto                      2477
#define rbTabsNone                      2478
#define tInsideSyncDir                  2479
#define cbNumberInCaption               2480
#define cbTabsLocationBottom            2481
#define rbTabsLocationTop               2482
#define rbTabsLocationBottom            2483
#define vkGlobalRestore                 2484
#define vkPasteFilePath                 2485
#define vkPasteDirectory                2486
#define rbScrollbarHide                 2487
#define rbScrollbarShow                 2488
#define rbScrollbarAuto                 2489
#define stHideCaptionAlwaysFrame        2490
#define cbTaskbarOverlay                2491
#define vkPasteCygwin                   2492
#define cbCmdTasksActive                2493
#define vkTabMenu2                      2494
#define vkSystemMenu2                   2495
#define cbStatusSystemColors            2496
#define stStatusColorBack               2497
#define stStatusColorLight              2498
#define stStatusColorDark               2499
#define vkWinAltK                       2500
#define vkCloseTab                      2501
#define vkCloseConEmu                   2502
#define vkDuplicateRoot                 2503
#define vkDuplicateRootAs               2504
#define lbStatusAvailable               2505
#define lbStatusSelected                2506
#define cbStatusAddAll                  2507
#define cbStatusAddSelected             2508
#define cbStatusDelAll                  2509
#define cbStatusDelSelected             2510
#define vkTabPane                       2511
#define vkTabPaneShift                  2512
#define vkCloseGroup                    2513
#define cbHotkeysAssignedOnly           2514
#define cbDefaultTerminal               2515
#define tDefaultTerminal                2516
#define cbCloseEditViewConfirm          2517
#define cbDefaultTerminalNoInjects      2518
#define rbDefaultTerminalConfAuto       2519
#define rbDefaultTerminalConfAlways     2520
#define rbDefaultTerminalConfNever      2521
#define vkDeleteLeftWord                2522
#define cbCTSDeleteLeftWord             2526
#define rCursorH                        2530
#define rCursorV                        2531
#define rCursorB                        2532
#define rCursorR                        2533
#define rInactiveCursorH                2534
#define rInactiveCursorV                2535
#define rInactiveCursorB                2536
#define rInactiveCursorR                2537
#define cbInactiveCursorColor           2538
#define cbInactiveCursorIgnoreSize      2539
#define tInactiveCursorFixedSize        2540
#define stInactiveCursorFixedSize       2541
#define stInactiveCursorMinSize         2542
#define tInactiveCursorMinSize          2543
#define cbInactiveCursor                2544
#define cbInactiveCursorBlink           2545
#define vkEscNoConsoles                 2546
#define cbDefaultTerminalStartup        2547
#define cbMultiShowButtons              2549
#define cbCTSShiftArrowStartSel         2553
#define vkCTSShiftLeft                  2554
#define vkCTSShiftRight                 2555
#define vkCTSShiftUp                    2556
#define vkCTSShiftDown                  2557
#define gbSelectingOverride             2558
#define rbMinByEscAlways                2559
#define rbMinByEscEmpty                 2560
#define rbMinByEscNever                 2561
#define cbHideChildCaption              2562
#define cbMapShiftEscToEsc              2563
#define tQuakeAnimation                 2564
#define stQuakeAnimation                2565
#define vkSetFocusSwitch                2566
#define cbMinimizeOnLoseFocus           2567
#define cbFocusInChildWindows           2568
#define tOptionSearch                   2569
#define tStorage                        2571
#define cbExportConfig                  2572
#define stStorage                       2573
#define vkSetFocusGui                   2575
#define vkSetFocusChild                 2576
#define vkChildSystemMenu               2577
#define cbSingleInstance                2578
#define cbCTSEndCopyBefore              2579
#define IDC_HELP_DESCR                  2580
#define vkJumpNextMonitor               2581
#define vkJumpPrevMonitor               2582
#define cbAddConEmuBase2Path            2584
#define cbCloseConEmuOnCrossClicking    2585
#define cbMinimizeOnLastTabClose        2586
#define cbHideOnLastTabClose            2587
#define cbCloseConEmuWithLastTab        2588
#define rbAutoUpdateStableFast          2589
#define rbAutoUpdatePreviewFast         2590
#define rbAutoUpdateDeveloperFast       2591
#define cbShowHelpTooltips              2592
#define tTabBtnDblClickAction           2593
#define cbIntegralSize                  2594
#define vkCTSVkCopyAll                  2595
#define vkTileToLeft                    2596
#define vkTileToRight                   2597
#define cbSuppressBells                 2598
#define cbOneTabPerGroup                2599
#define tTabBarDblClickAction           2600
#define cbActivateSplitMouseOver        2601
#define tPerfCounters                   2602
#define cbCTSIBeam                      2603
#define vkSplitNewConV                  2604
#define vkSplitNewConH                  2605
#define vkSplitSizeVup                  2606
#define vkSplitSizeVdown                2607
#define vkSplitSizeHleft                2608
#define vkSplitSizeHright               2609
#define vkSplitFocusUp                  2610
#define vkSplitFocusDown                2611
#define vkSplitFocusLeft                2612
#define vkSplitFocusRight               2613
#define cbClinkWebPage                  2614
#define cbStatusVertPad                 2615
#define cbActionChk1                    2616
#define stActionTitle                   2617
#define cbActionBtn1                    2618
#define cbActionBtn2                    2619
#define cbActionBtn3                    2620
#define vkCloseGroupPrc                 2621
#define cbConsoleExceptionHandler       2622
#define lbStorageLocation               2623
#define vkMultiNewPopup2                2624
#define vkCloseAllCon                   2625
#define vkCloseExceptCon                2626
#define cbDefaultTerminalTSA            2627
#define tCmdGroupKey                    2628
#define cbCmdGroupKey                   2629
#define vkCTSShiftHome                  2630
#define vkCTSShiftEnd                   2631
#define cbAddDefaults                   2632
#define vkCTSCopyHtml0                  2633
#define vkCTSCopyHtml1                  2634
#define vkCTSCopyHtml2                  2635
#define vkMaximizeWidth                 2636
#define vkMaximizeHeight                2637
#define cbProcessNewConArg              2640
#define cbHighlightMouseRow             2641
#define cbHighlightMouseCol             2642
#define vkHighlightMouse                2646
#define vkTransparencyInc               2647
#define vkTransparencyDec               2648
#define pLinkDonate                     2649
#define pLinkFlattr                     2650
#define pIconCtrl                       2651
#define cbTaskbarProgress               2656
#define cbCTSIntelligent                2657
#define tCTSIntelligentExceptions       2658
#define stCTSIntelligentExceptions      2659
#define gbDefaultTermConfClose          2660
#define cbDefaultTerminalUseExisting    2661
#define stDefaultTerminalSwitchInfo     2662
#define stDefaultTerminal               2663
#define bImportSettings                 2664
#define cbRetardInactivePanes           2665
#define stFontCharset                   2666
#define stFontSizeY                     2667
#define stFontSizeX                     2668
#define stFontSizeX3                    2669
#define stFontSizeX2                    2670
#define stBgImage                       2671
#define stDarker                        2672
#define stDarkerPlugin                  2673
#define gbBgImage                       2674
#define gbFixFarBorders                 2675
#define gbExtendFonts                   2676
#define gbAntiAliasing                  2677
#define gbMainConFont                   2678
#define cbAnsiLog                       2679
#define tAnsiLogPath                    2680
#define stGotoEditorCmdHelp             2681
#define tAboutSearch                    2682
#define stConEmuVersion                 2683
#define cbDefTermAgressive              2684
#define stDefTermWikiLink               2685
#define gbConfirmActions                2686
#define gbConfirmMisc                   2687
#define cbDupConfirm                    2688
#define cbConfirmDetach                 2689
#define cbFontMonitorDpi                2691
#define cbFontAsDeviceUnits             2692
#define vkAppsPgUp                      2693
#define vkAppsPgDn                      2694
#define vkAppsHome                      2695
#define vkAppsEnd                       2696
#define vkAppsBS                        2697
#define vkFontOriginal                  2698
#define cbHotKeyChord                   2699
#define hkHotKeySelect2                 2701
#define gbHistorySettings               2704
#define cbSaveCmdHistory                2705
#define tCmdHistoryLocation             2706
#define cbCmdHistoryLocation            2707
#define lbHistoryItems                  2709
#define cbHistoryClearAll               2710
#define cbHistoryDelItem                2711
#define stHistoryItems                  2712
#define vkCloseZombies                  2713
#define stCTSPreview                    2714
#define cbMultiShowSearch               2715
#define cbColorResetExt                 2716
#define rbColorRgbDec                   2720
#define rbColorRgbHex                   2721
#define rbColorBgrHex                   2722
#define vkHighlightMouseX               2725
#define vkWinAltT                       2726
#define vkMultiPause                    2727
#define vkMultiGroup                    2728
#define vkMaximizePane                  2729
#define stTabFontFace                   2730
#define stTabFontCharset                2731
#define stTabBtnDblClickAction          2732
#define stTabBarDblClickAction          2733
#define stTabConsole                    2735
#define stTabTemplateGroup              2736
#define stTabTemplateDescr              2737
#define tTabModifiedSuffix              2738
#define tTabFlashCounter                2739
#define cbProcessCmdStart               2740
#define stStorageLocation               2741
#define stSingleInstance                2742
#define stUseKeyboardHooksFast          2743
#define stInjectConEmuHkFast            2744
#define gbFastConfig                    2745
#define gbFeatureInConsole              2746
#define gbFeatureDebug                  2747
#define gbFeatureRetard                 2748
#define cbCmdGrpDefaultNew              2750
#define cbCmdGrpDefaultCmd              2751
#define cbCmdGrpTaskbar                 2752
#define cbCmdGrpToolbar                 2753
#define gbStartGroupCommands            2754
#define tStartGroupCommands             2755
#define gbConfirmClose                  2756
#define cbCloseWindowConfirm            2757
#define cbConfirmCloseRunning           2758
#define gbConfirmCloseFar               2759
#define vkWinAltH                       2760
#define vkTermButShell                  2761
#define stPriorityBox                   2762
#define rbPriorityRealtime              2763
#define rbPriorityHigh                  2764
#define rbPriorityAbove                 2765
#define rbPriorityNormal                2766
#define rbPriorityBelow                 2767
#define rbPriorityIdle                  2768
#define stAffinityBox                   2769
#define cbAffinity0                     2770
#define cbAffinity1                     2771
#define cbAffinity2                     2772
#define cbAffinity3                     2773
#define cbAffinity4                     2774
#define cbAffinity5                     2775
#define cbAffinity6                     2776
#define cbAffinity7                     2777
#define cbAffinity8                     2778
#define cbAffinity9                     2779
#define cbAffinity10                    2780
#define cbAffinity11                    2781
#define cbAffinity12                    2782
#define cbAffinity13                    2783
#define cbAffinity14                    2784
#define cbAffinity15                    2785
#define cbAffinity16                    2786
#define cbAffinity17                    2787
#define cbAffinity18                    2788
#define cbAffinity19                    2789
#define cbAffinity20                    2790
#define cbAffinity21                    2791
#define cbAffinity22                    2792
#define cbAffinity23                    2793
#define cbAffinity24                    2794
#define cbAffinity25                    2795
#define cbAffinity26                    2796
#define cbAffinity27                    2797
#define cbAffinity28                    2798
#define cbAffinity29                    2799
#define cbAffinity30                    2800
#define cbAffinity31                    2801
#define cbAffinity32                    2802
#define cbAffinity33                    2803
#define cbAffinity34                    2804
#define cbAffinity35                    2805
#define cbAffinity36                    2806
#define cbAffinity37                    2807
#define cbAffinity38                    2808
#define cbAffinity39                    2809
#define cbAffinity40                    2810
#define cbAffinity41                    2811
#define cbAffinity42                    2812
#define cbAffinity43                    2813
#define cbAffinity44                    2814
#define cbAffinity45                    2815
#define cbAffinity46                    2816
#define cbAffinity47                    2817
#define cbAffinity48                    2818
#define cbAffinity49                    2819
#define cbAffinity50                    2820
#define cbAffinity51                    2821
#define cbAffinity52                    2822
#define cbAffinity53                    2823
#define cbAffinity54                    2824
#define cbAffinity55                    2825
#define cbAffinity56                    2826
#define cbAffinity57                    2827
#define cbAffinity58                    2828
#define cbAffinity59                    2829
#define cbAffinity60                    2830
#define cbAffinity61                    2831
#define cbAffinity62                    2832
#define cbAffinity63                    2833
#define vkAffinity                      2834
#define tUnicodeRanges                  2835
#define stExtendFonts                   2836
#define stUnicodeRanges                 2837
#define cbUnicodeRangesApply            2838
#define vkConDetach                     2839
#define vkConUnfasten                   2840
#define lbStartupShellFast              2842
#define stStartupShellFast              2843
#define lbColorSchemeFast               2844
#define stColorSchemeFast               2845
#define cbQuakeFast                     2846
#define tQuakeKeyFast                   2847
#define cbQuakeKeyFast                  2848
#define stPalettePreviewFast            2849
#define gbSetAlias                      2850
#define tSetCommands                    2851
#define stSetCommands                   2852
#define vkCdExplorerPath                2853
#define cbShowWasSetOnTopMsg            2854
#define stSetCommands2                  2855
#define cbUpdateInetTool                2856
#define tUpdateInetTool                 2857
#define cbUpdateInetToolPath            2858
#define stUpdateCommand                 2859
#define stUpdatePostCommand             2860
#define stUpdateVerLocation             2861
#define stUpdateReleaseType             2862
#define stUpdateCheck                   2863
#define gbUpdate                        2864
#define cbApplyDefTerm                  2865
#define cbDefaultTerminalDebugLog       2866
#define cbRestore2ActiveMonitor         2867
#define gbStartupOptions                2868
#define gbTaskStartDelay                2869
#define stStartCreateDelay              2870
#define tStartCreateDelay               2871
#define stCopyFormat                    2872
#define lbCopyFormat                    2873
#define vkDebugProcess                  2874
#define vkDumpProcess                   2875
#define vkDumpTree                      2876
#define cbUpdateCheck                   2877
#define cbProcessCtrlZ                  2878
#define cbFont2AA                       2883
#define stCmdTaskAdd                    2884
#define stKeySelect                     2885
#define gbWindowSizePos                 2889
#define gbWindowPos                     2890
#define stWindowPosX                    2891
#define stWindowPosY                    2892
#define gbWindowSize                    2893
#define gbConsoleBuffer                 2894
#define gbNtvdm                         2895
#define stNtvdmHeight                   2896
#define gbVConAlignment                 2897
#define stVConPadSize                   2898
#define gbShowGeneric                   2900
#define gbShowScrollBar                 2901
#define stScrollAppear                  2902
#define stScrollDisappear               2903
#define stFrameWidth                    2904
#define stFrameAppear                   2905
#define stFrameDisappear                2906
#define gbQuakeStyle                    2907
#define gbTaskBarNotify                 2908
#define gbTaskBarButton                 2909
#define gbWndCloseAction                2910
#define gbMinimizeAction                2911
#define gbMinimizeOnEsc                 2912
#define gbCursorActive                  2913
#define gbCursorInactive                2914
#define gbIntgrHere                     2915
#define gbIntgrInside                   2916
#define stIntgrHereItem                 2917
#define stIntgrHereCfg                  2918
#define stIntgrHereCmd                  2919
#define stIntgrHereIcon                 2920
#define stIntgrInsideNote               2921
#define stIntgrInsideItem               2922
#define stIntgrInsideCfg                2923
#define stIntgrInsideCmd                2924
#define stIntgrInsideIcon               2925
#define gbDefTerm                       2926
#define gbExtendColors                  2927
#define gbColorEnhancement              2928
#define stColorFadeLow                  2929
#define stColorFadeHigh                 2930
#define stColorSchemes                  2931
#define stColorText                     2932
#define stColorBack                     2933
#define stColorPopupText                2934
#define stColorPopupBack                2935
#define gbAlphaTransparency             2936
#define stTransparentActive             2937
#define stOpaqueActive                  2938
#define gbStaticTransparency            2939
#define stFarPID                        2940
#define stRConStates                    2941
#define gbInfoProcesses                 2942
#define gbInfoSizes                     2943
#define gbInfoCmdLine                   2944
#define stConsoleSizeChars              2945
#define stConsoleSizePixels             2946
#define stDcWndSize                     2947
#define stRConCursorInfo                2948
#define stFarPanelLeft                  2949
#define stFarPanelRight                 2950
#define gbVConFont                      2951
#define stVConFontMain                  2952
#define stVConFontFix                   2953
#define stCmdOutputCP                   2954
#define gbCmdAutoAttach                 2955
#define stCmdAutoAttach                 2956
#define gbFarDragDrop                   2957
#define gbFarOptions                    2958
#define gbFarTabTemplates               2959
#define stFarTabTemplates               2960
#define stTabPanels                     2961
#define stTabEditor                     2962
#define stTabViewer                     2963
#define stTabEditorMod                  2964
#define gbFarMacros                     2965
#define stCloseTabMacro                 2966
#define stSaveAllMacro                  2967
#define stStartupDir                    2968
#define stRunAsUser                     2969
#define stRunAsPassword                 2970
#define gbRunAsOptions                  2971
#define gbHyperlinks                    2972
#define gbHighlightRowCol               2973
#define gbAddToPath                     2974
#define gbTextSelection                 2975
#define gbSelectColorIdx                2976
#define stCTSTextColor                  2977
#define stCTSBackColor                  2978
#define gbSelectMouse                   2979
#define gbSelectKeyboard                2980
#define gbTabs                          2981
#define stTabModifiedSuffix             2982
#define stTabFlashCounter               2983
#define stTabSkipWords                  2984
#define stTabLenMax                     2985
#define gbStatusFontColor               2986
#define stStatusFontFace                2987
#define stStatusFontCharset             2988
#define stStatusLines                   2989
#define stStatusAvailCol                2990
#define stStatusSelCol                  2991
#define gbFarPanelViews                 2992
#define gbFarThumbnails                 2993
#define gbFarTiles                      2994
#define stThumbsFontName                2995
#define stThumbsImgSize                 2996
#define stThumbsSpacing                 2997
#define stThumbsPadding                 2998
#define stTilesFontName                 2999
#define stTilesImgSize                  3000
#define stTilesSpacing                  3001
#define stTilesPadding                  3002
#define stThumbMaxZoom                  3003
#define stThumbLoadingTimeout           3004
#define gbFarPreviewBg                  3005
#define stMoreConfont1                  3006
#define stMoreConfont2                  3007
#define stMoreConfont3                  3008
#define stMoreConfont4                  3009
#define stMoreConfont5                  3010
#define stMoreConfont6                  3011
#define stConsoleFontSizeY              3012
#define stConsoleFontSizeX              3013
#define gbHotkeys                       3014
#define stHotkeys                       3015
#define gbCtrlMouse                     3016
#define gbCtrlIntercept                 3017
#define gbCtrlSeizeKeys                 3018
#define gbCtrlMisc                      3019
#define gbCtrlPrompt                    3020
#define gbCtrlMouseBtns                 3021
#define stCTSRBtnAction                 3022
#define stCTSMBtnAction                 3023
#define stCmdGroupKey                   3024
#define stKeySelectMod                  3025
#define vkJumpActiveMonitor             3026
#define vkResetTerminal                 3027
#define vkAltNumpad                     3028
#define cbCTSResetOnRelease             3029
#define cbCTSEraseBeforeReset           3030
#define cbDebugLog                      3031
#define tDebugLogDir                    3032
#define rPasteM1MultiLine               3033
#define rPasteM1SingleLine              3034
#define rPasteM1FirstLine               3035
#define rPasteM1Nothing                 3036
#define rPasteM2MultiLine               3040
#define rPasteM2SingleLine              3041
#define rPasteM2FirstLine               3042
#define rPasteM2Nothing                 3043
#define gbPasteM1                       3047
#define gbPasteM2                       3048
#define gbPasteConfirm                  3049
#define stBgReplaceIndexes              3051
#define tHotkeysFilter                  3052
#define lbHotKeyFilter                  3053
#define stElevatedConsolesGroup         3054
#define gbTabDblClkActions              3055
#define cbVividColors                   3056
#define rbActivityProcess               3057
#define gbQuakeFrame                    3058
#define gbChildGui                      3059
#define cbMouseDragWindow               3060
#define cbUseAltGrayPlus                3061
#define stCTSRMCondition                3062
#define gbAnsiSecureExec                3063
#define stAnsiSecureExec1               3064
#define stAnsiSecureExec2               3065
#define stAnsiSecureExecUrl             3066
#define rbAnsiSecureAny                 3067
#define rbAnsiSecureCmd                 3068
#define rbAnsiSecureOff                 3069
#define tAnsiSecure                     3070
#define stAnsiSecureExec3               3071
#define gbAnsiSequences                 3072
#define cbJumpListAutoUpdate            3073
#define cbCompressLongStrings           3074
#define cbKillSshAgent                  3075
#define vkFindPrevPrompt                3076
#define vkFindNextPrompt                3077
#define IDC_ATTACH_LEAVE_OPEN           3078
#define vkMultiGroupAll                 3079
#define vkSplitSwapUp                   3080
#define vkSplitSwapDown                 3081
#define vkSplitSwapLeft                 3082
#define vkSplitSwapRight                3083
#define vkSplitSwap                     3084
#define vkMultiGroupKey                 3085
#define stRestartCmd                    3086
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         3087
#define _APS_NEXT_SYMED_VALUE           130
#endif
#endif
