//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource.rc
//
#define IDI_ICON1                       1
#define IDI_ICON2                       2
#define IDI_ICON3                       3
#define bSaveSettings                   4
#define IDD_DIALOG1                     101
#define IDB_CONMAN1                     101
#define IDD_DIALOG2                     103
#define IDD_DIALOGM                     104
#define IDD_DIALOG3                     105
#define IDC_COPY                        108
#define IDC_LINK                        109
#define IDC_MOVE                        110
#define IDD_RESTART                     112
#define c0                              1000
#define c1                              1001
#define c2                              1002
#define c3                              1003
#define c4                              1004
#define c5                              1005
#define c6                              1006
#define c7                              1007
#define c8                              1008
#define c9                              1009
#define c10                             1010
#define c11                             1011
#define c12                             1012
#define c13                             1013
#define c14                             1014
#define c15                             1015
#define c16                             1016
#define c17                             1017
#define c18                             1018
#define c19                             1019
#define c20                             1020
#define c21                             1021
#define c22                             1022
#define c23                             1023
#define c24                             1024
#define c25                             1025
#define c26                             1026
#define c27                             1027
#define c28                             1028
#define c29                             1029
#define c30                             1030
#define c31                             1031
#define cbRClick                        1034
#define tBgImage                        1037
#define tDarker                         1038
#define cbBgImage                       1039
#define cbBold                          1041
#define tFontSizeX                      1042
#define cbItalic                        1043
#define tWndWidth                       1045
#define tWndHeight                      1046
#define cbMonospace                     1047
#define cbNonProportional               1048
#define tFontSizeX2                     1049
#define slDarker                        1050
#define cbSendAE                        1051
#define cbDnDCopy                       1053
#define cbTabs                          1054
#define cbGUIpb                         1055
#define tFontSizeX3                     1056
#define bBgImage                        1057
#define rBgStretch                      1058
#define rBgTile                         1059
#define rBgSimple                       1060
#define tWndX                           1061
#define tWndY                           1062
#define cbPosFixed                      1064
#define tabMain                         1066
#define lbExtendIdx                     1067
#define cbVisualizer                    1068
#define lbVisNormal                     1069
#define lbVisTab                        1070
#define lbVisEOL                        1071
#define lbVisEOF                        1072
#define lbVisFore                       1073
#define cbAutoConHandle                 1074
#define rCascade                        1075
#define rFixed                          1076
#define cbsConManActive                 1078
#define cbsTelnetActive                 1079
#define cbsFarActive                    1080
#define cbsFilePanel                    1081
#define cbsPlugin                       1082
#define cbsEditor                       1083
#define cbsViewer                       1084
#define lbProcesses                     1085
#define cbsNtvdmActive                  1086
#define tc0                             1100
#define tc1                             1101
#define tc2                             1102
#define tc3                             1103
#define tc4                             1104
#define tc5                             1105
#define tc6                             1106
#define tc7                             1107
#define tc8                             1108
#define tc9                             1109
#define tc10                            1110
#define tc11                            1111
#define tc12                            1112
#define tc13                            1113
#define tc14                            1114
#define tc15                            1115
#define tc16                            1116
#define tc17                            1117
#define tc18                            1118
#define tc19                            1119
#define tc20                            1120
#define tc21                            1121
#define tc22                            1122
#define tc23                            1123
#define tc24                            1124
#define tc25                            1125
#define tc26                            1126
#define tc27                            1127
#define tc28                            1128
#define tc29                            1129
#define tc30                            1130
#define tc31                            1131
#define bChooseFont                     1201
#define rNoneAA                         1202
#define rStandardAA                     1203
#define rCTAA                           1204
#define cbFullScreen                    1205
#define tFont                           1206
#define cbFixFarBorders                 1207
#define rCursorV                        1208
#define rCursorH                        1209
#define cbCursorColor                   1210
#define rNormal                         1311
#define rMaximized                      1312
#define rFullScreen                     1313
#define gbPerformance                   1400
#define tPerfFPS                        1401
#define tPerfRender                     1402
#define tPerfBlt                        1403
#define tPerfInterval                   1404
#define lbLDragKey                      1501
#define cbDropEnabled                   1502
#define lbRDragKey                      1503
#define cbDragL                         1504
#define cbDragR                         1505
#define cbConMan                        1506
#define cbMinToTray                     1507
#define tCurCmdLine                     1508
#define tsConManIdx                     1509
#define tsTopPID                        1510
#define tFontFace                       1511
#define tFontSizeY                      1512
#define tConSizeChr                     1512
#define tFontCharset                    1513
#define tConSizePix                     1513
#define tFontFace2                      1514
#define tDCSize                         1514
#define cbExtendColors                  1515
#define tPanelLeft                      1515
#define tCmdLine                        1516
#define tPanelRight                     1516
#define cbsAltActive                    1517
#define cbApplyPos                      1520
#define cbCursorBlink                   1522
#define IDC_RESTART_ICON                1523
#define IDC_START                       1524
#define IDC_TERMINATE                   1525
#define IDC_RESTART_CMD                 1527
#define IDC_CHOOSE                      1528
#define IDC_RESTART_MSG                 1529
#define IDC_WARNING                     1530

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1531
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
