//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ConEmu.rc
//
#define IDI_ICON1                       1
#define IDI_ICON2                       2
#define IDI_ICON3                       3
#define IDB_MAIN_TOOLBAR                101
#define IDB_SHIELD                      102
#define IDB_RIGHTCLICKING               103
#define IDB_COPY                        104
#define IDC_COPY                        120
#define IDC_LINK                        121
#define IDC_MOVE                        122
#define IDD_RESTART                     123
#define IDC_SPLITV                      124
#define IDC_SPLITH                      125
#define IDD_SETTINGS                    150
#define IDD_SPG_MAIN                    151
#define IDD_SPG_COLORS                  152
#define IDD_SPG_INFO                    153
#define IDD_SPG_FEATURE                 154
#define IDD_SPG_DEBUG                   155
#define IDD_MORE_HIDE                   200
#define IDD_DIALOG1                     202
#define IDD_MORE_FADE                   203
#define IDD_MORE_SELECTION              204
#define IDD_SPG_TABS                    206
#define IDD_SPG_VIEWS                   208
#define IDD_MORE_CONFONT                209
#define IDD_MORE_DOSBOX                 210
#define IDD_SPG_KEYS                    211
#define c0                              1000
#define c1                              1001
#define c2                              1002
#define c3                              1003
#define c4                              1004
#define c5                              1005
#define c6                              1006
#define c7                              1007
#define c8                              1008
#define c9                              1009
#define c10                             1010
#define c11                             1011
#define c12                             1012
#define c13                             1013
#define c14                             1014
#define c15                             1015
#define c16                             1016
#define c17                             1017
#define c18                             1018
#define c19                             1019
#define c20                             1020
#define c21                             1021
#define c22                             1022
#define c23                             1023
#define c24                             1024
#define c25                             1025
#define c26                             1026
#define c27                             1027
#define c28                             1028
#define c29                             1029
#define c30                             1030
#define c31                             1031
#define c32                             1032
#define c33                             1033
#define c34                             1034
#define cbBold                          1041
#define tFontSizeX                      1042
#define cbItalic                        1043
#define tWndWidth                       1045
#define tWndHeight                      1046
#define cbMonospace                     1048
#define tFontSizeX2                     1049
#define slDarker                        1050
#define cbSendAE                        1051
#define cbDnDCopy                       1053
#define cbTabs                          1054
#define cbEnhanceGraphics               1055
#define tFontSizeX3                     1056
#define bBgImage                        1057
#define rBgUpLeft                       1058
#define rBgStretch                      1059
#define rBgTile                         1060
#define tWndX                           1061
#define tWndY                           1062
#define cbPosFixed                      1064
#define tabMain                         1066
#define lbExtendIdx                     1067
#define lbExtendFontItalicIdx           1068
#define lbExtendFontNormalIdx           1069
#define rCascade                        1075
#define rFixed                          1076
#define lbProcesses                     1085
#define tc0                             1100
#define tc1                             1101
#define tc2                             1102
#define tc3                             1103
#define tc4                             1104
#define tc5                             1105
#define tc6                             1106
#define tc7                             1107
#define tc8                             1108
#define tc9                             1109
#define tc10                            1110
#define tc11                            1111
#define tc12                            1112
#define tc13                            1113
#define tc14                            1114
#define tc15                            1115
#define tc16                            1116
#define tc17                            1117
#define tc18                            1118
#define tc19                            1119
#define tc20                            1120
#define tc21                            1121
#define tc22                            1122
#define tc23                            1123
#define tc24                            1124
#define tc25                            1125
#define tc26                            1126
#define tc27                            1127
#define tc28                            1128
#define tc29                            1129
#define tc30                            1130
#define tc31                            1131
#define tc32                            1132
#define tc33                            1133
#define tc34                            1134
#define bChooseFont                     1201
#define rNoneAA                         1202
#define rStandardAA                     1203
#define rCTAA                           1204
#define cbFullScreen                    1205
#define tFont                           1206
#define cbFixFarBorders                 1207
#define rCursorV                        1208
#define rCursorH                        1209
#define cbCursorColor                   1210
#define rNormal                         1311
#define rMaximized                      1312
#define rFullScreen                     1313
#define gbPerformance                   1400
#define tPerfFPS                        1401
#define tPerfData                       1402
#define tPerfRender                     1403
#define tPerfBlt                        1404
#define tPerfInterval                   1405
#define lbLDragKey                      1501
#define cbDropEnabled                   1502
#define lbRDragKey                      1503
#define cbDragL                         1504
#define cbDragR                         1505
#define cbMultiCon                      1506
#define cbMinToTray                     1507
#define tCurCmdLine                     1508
#define tsTopPID                        1510
#define tFontFace                       1511
#define tFontSizeY                      1512
#define tFontCharset                    1513
#define tFontFace2                      1514
#define cbExtendColors                  1515
#define tCmdLine                        1516
#define tRealFontMain                   1517
#define tRealFontBorders                1518
#define cbApplyPos                      1520
#define cbCursorBlink                   1522
#define IDC_RESTART_ICON                1523
#define IDC_START                       1524
#define IDC_TERMINATE                   1525
#define IDC_RESTART_CMD                 1527
#define IDC_CHOOSE                      1528
#define IDC_RESTART_MSG                 1529
#define IDC_WARNING                     1530
#define cbTabSelf                       1531
#define cbTabLazy                       1532
#define cbTabRecent                     1533
#define cbLongOutput                    1534
#define tLongOutputHeight               1535
#define cbRSelectionFix                 1536
#define cbMonitorConsoleLang            1537
#define cbSkipFocusEvents               1538
#define hkNewConsole                    1539
#define hkSwitchConsole                 1540
#define hkDelConsole                    1541
#define cbSkipActivation                1542
#define cbSkipMove                      1543
#define gbStandardColors                1544
#define cbVisible                       1545
#define cbNewConfirm                    1546
#define cbRunAsAdmin                    1547
#define cbDragImage                     1548
#define cbAutoRegFonts                  1550
#define cbDebugSteps                    1551
#define cbDragIcons                     1553
#define lbDefaultColors                 1554
#define lbCmdOutputCP                   1558
#define lbNtvdmHeight                   1559
#define IDC_CONSOLE_STATES              1560
#define cbFARuseASCIIsort               1561
#define cbFixAltOnAltTab                1562
#define cbFarHourglass                  1563
#define slTransparent                   1564
#define cbHideCaption                   1565
#define cbFontAuto                      1566
#define cbDragPanel                     1568
#define cbHideCaptionAlways             1569
#define cbTryToCenter                   1570
#define cbDesktopMode                   1571
#define cbAlwaysOnTop                   1572
#define cbUserScreenTransparent         1573
#define cbTransparent                   1574
#define tBgImageColors                  1575
#define cbExtendFonts                   1576
#define lbExtendFontBoldIdx             1577
#define cbTrueColorer                   1578
#define cbDropUnlocked                  1579
#define cbDropUseBCopy                  1580
#define cbFadeInactive                  1581
#define cbBlockInactiveCursor           1586
#define bHideCaptionSettings            1588
#define tHideCaptionAlwaysFrame         1589
#define tHideCaptionAlwaysDelay         1590
#define tHideCaptionAlwaysDissapear     1591
#define bMultiConHotkeys                1592
#define cbMultiConKeybHooks             1593
#define cbToolbar                       1593
#define bTabTemplates                   1594
#define bResetSettings                  1595
#define bReloadSettings                 1596
#define tConSizeChr                     1597
#define tConSizePix                     1598
#define tDCSize                         1599
#define tPanelLeft                      1600
#define tPanelRight                     1601
#define IDC_CHOOSE_DIR                  1602
#define IDC_STARTUP_DIR                 1603
#define hkStartCmd                      1604
#define hkCloseConsole                  1605
#define bFarHourglass                   1606
#define bRClick                         1607
#define bRealConsoleSettings            1608
#define bDropSettings                   1609
#define bSaveSettings                   1610
#define cbHostWin                       1611
#define cbHostApps                      1612
#define cbHostLCtrl                     1613
#define cbHostRCtrl                     1614
#define cbHostLAlt                      1615
#define cbHostRAlt                      1616
#define cbHostLShift                    1617
#define cbHostRShift                    1618
#define cbHandleFarDetach               1619
#define cbConsoleTextSelection          1620
#define cbPortableRegistry              1621
#define tCursorPos                      1622
#define tFadeLow                        1624
#define tFadeHigh                       1625
#define bConsoleTextSelection           1627
#define bCTSSettings                    1627
#define rbCTSAlways                     1628
#define rbCTSBufferOnly                 1629
#define cbCTSTextSelection              1630
#define lbCTSMBtnAction                 1631
#define lbCTSRBtnAction                 1632
#define lbCTSBlockSelection             1633
#define lbCTSTextSelection              1634
#define cbCTSBlockSelection             1635
#define lbCTSForeIdx                    1636
#define lbCTSBackIdx                    1637
#define tTabConsole                     1638
#define lbCTSActAlways                  1638
#define tTabEditor                      1639
#define tTabViewer                      1640
#define tTabEditorMod                   1641
#define cbHideInactiveConTabs           1642
#define tTabLenMax                      1643
#define cbHideInactiveConTabs2          1644
#define cbAdminShield                   1646
#define tAdminSuffix                    1647
#define cbUseWinNumber                  1648
#define cbInstallKeybHooks              1649
#define cbRunAsRestricted               1650
#define tRunAsUser                      1652
#define tRunAsPassword                  1653
#define cbSafeFarClose                  1654
#define cbIgnoreTelnetCursorSize        1655
#define rbCurrentUser                   1656
#define rbAnotherUser                   1657
#define tThumbsFontName                 1659
#define tThumbsFontSize                 1660
#define tTilesFontName                  1661
#define tThumbMaxZoom                   1662
#define cbThumbLoadFolders              1663
#define cbThumbLoadFiles                1664
#define tThumbFullSize                  1665
#define tThumbsImgSize                  1665
#define tTilesFontSize                  1666
#define cbThumbPreviewBox               1667
#define cbThumbSelectionBox             1668
#define tThumbLabelHeight               1669
#define tTilesImgSize                   1669
#define rbThumbBackColorIdx             1670
#define rbThumbBackColorRGB             1671
#define lbThumbBackColorIdx             1672
#define rbThumbPreviewBoxColorIdx       1673
#define rbThumbPreviewBoxColorRGB       1674
#define lbThumbPreviewBoxColorIdx       1675
#define rbThumbSelectionBoxColorIdx     1676
#define rbThumbSelectionBoxColorRGB     1677
#define lbThumbSelectionBoxColorIdx     1678
#define tThumbLoadingTimeout            1679
#define cbThumbUsePicView2              1680
#define rbThumbCachePluginFolder        1687
#define rbThumbCacheUserFolder          1688
#define rbThumbCacheDisabled            1689
#define rbThumbCacheSpecifiedFolder     1690
#define cbThumbCacheFolder              1691
#define tThumbCacheFolder               1692
#define cbRClick                        1696
#define tBgImage                        1697
#define tDarker                         1698
#define cbBgImage                       1699
#define tThumbSupportedExtensions       1700
#define cbTilesPreviewBox               1701
#define cbTilesSelectionBox             1702
#define tThumbsX1                       1703
#define tThumbsY1                       1704
#define tThumbsX2                       1705
#define tThumbsY2                       1706
#define tThumbsSpacing                  1707
#define tThumbsPadding                  1708
#define tTilesX1                        1709
#define tTilesY1                        1710
#define tTilesX2                        1711
#define tTilesY2                        1712
#define tTilesSpacing                   1713
#define tTilesPadding                   1714
#define bApplyViewSettings              1717
#define bConFontOK                      1717
#define cbActivityReset                 1717
#define bDosBoxSettings                 1717
#define cbDisableFarFlashing            1718
#define cbDisableAllFlashing            1719
#define cbThumbRestoreOnStartup         1720
#define cbSleepInBackground             1721
#define cbExtendUCharMap                1722
#define cbAutoSaveSizePos               1723
#define cbShellNoZoneCheck              1725
#define bConFontCancel                  1726
#define tConsoleFontFace                1727
#define tConsoleFontSizeY               1728
#define tConsoleFontSizeX               1729
#define bConFontAdd2HKLM                1730
#define tConsoleFontHklmNote            1731
#define tConsoleFontConsoleNote         1732
#define cbSendAltSpace                  1733
#define cbBgAllowPlugin                 1734
#define cbTabsInCaption                 1735
#define cbAlwaysShowTrayIcon            1736
#define rbCTSActAlways                  1737
#define rbCTSActBufferOnly              1738
#define cbAlwaysShowScrollbar           1739
#define cbLogShellActivity              1740
#define cbLogInputActivity              1741
#define lbActivityLog                   1742
#define gbActivityLog                   1744
#define cbActivitySaveAs                1746
#define rbActivityDisabled              1747
#define rbActivityShell                 1748
#define ebActivityApp                   1750
#define ebActivityParm                  1751
#define cbUseInjects                    1752
#define cbDosBoxForceConfig             1752
#define cbDosBox                        1753
#define ebDosBoxPath                    1754
#define bDosBoxPath                     1755
#define ebDosBoxForceConfig             1756
#define bDosBoxForceConfig              1757
#define ebDosBoxDrives                  1758
#define IDC_EDIT3                       1759
#define ebDosBoxAutoexec                1759
#define tsRConFlags                     1760
#define bPortableRegistrySettings       1761
#define rbActivityInput                 1762
#define cbUseWinTab                     1764
#define cbFarGotoEditor                 1765
#define lbFarGotoEditorVk               1766
#define hkHotKeySelect                  1767
#define cbUseWinArrows                  1768
#define stHotKeySelect                  1769
#define stHotModifierSelect             1770
#define lbConEmuHotKeys                 1771
#define hkMinRestore                    1772
#define hkBufferMode                    1773
#define vkMinimizeRestore               2000
#define vkMultiNew                      2001
#define vkMultiNext                     2002
#define vkMultiRecreate                 2003
#define vkMultiBuffer                   2004
#define vkMultiClose                    2005
#define vkMultiCmd                      2006
#define vkCTSVkBlock                    2007
#define vkCTSVkText                     2008
#define vkCTSVkAct                      2009
#define vkFarGotoEditorVk               2010
#define vkLDragKey                      2011
#define vkRDragKey                      2012
#define vkWinAltP                       2013
#define vkWinAltSpace                   2014
#define vkAltF9                         2015
#define vkCtrlWinAltSpace               2016
#define vkAltEnter                      2017
#define vkAltSpace                      2018
#define vkCtrlUp                        2019
#define vkCtrlDown                      2020
#define vkCtrlPgUp                      2021
#define vkCtrlPgDn                      2022
#define vkCtrlTab                       2023
#define vkCtrlShiftTab                  2024
#define vkCtrlTab_Left                  2025
#define vkCtrlTab_Right                 2026
#define vkCtrlTab_Up                    2027
#define vkCtrlTab_Down                  2028
#define vkCtrlWinEnter                  2029
#define vkMultiNextShift                2030
#define vkConsole_1                     2031
#define vkConsole_2                     2032
#define vkConsole_3                     2033
#define vkConsole_4                     2034
#define vkConsole_5                     2035
#define vkConsole_6                     2036
#define vkConsole_7                     2037
#define vkConsole_8                     2038
#define vkConsole_9                     2039
#define vkConsole_10                    2040
#define vkConsole_11                    2041
#define vkConsole_12                    2042
#define vkMultiNewShift                 2043
#define vkWinLeft                       2044
#define vkWinRight                      2045
#define vkWinUp                         2046
#define vkWinDown                       2047

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1774
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
