
#pragma once

enum {
	CEPluginName=0,
	CEMenuThumbnails,
	CEMenuTiles,
	CEMenuIcons,
	CEColTitleThumbnails,
	CEColTitleTiles,
	CEDirFolder,
	CEDirSymLink,
	CEDirJunction,
	CEPluginNotFound,
	CEOldPluginVersion,
	CEFarNonGuiMode,
	CEInvalidPanelSettings,
	CENoPlaceForIcons,
	CEBisReqForIcons,
	CECreateThreadFailed,
	CEThreadActivationFailed,
	CEPostThreadMessageFailed,
	CEDisplayThreadTerminated,
	CERegisterClassFailed,
	CECreateWindowFailed,
	CEGuiDontAcceptPanel,
	CEUnknownPanelMode,
	CEInvalidSettingValues,
	CEUnavailableInTerminal,
	};
